<?php
// This script and data application were generated by AppGini 5.75
// Download AppGini for free from https://bigprof.com/appgini/download/

/*
	ajax-callable script that returns code for either a combo drop-down or an auto-complete
	drop-down, based on number of items.

	REQUEST parameters:
	===============
	t: table name
	f: lookup field name
	id: selected id
	p: page number (default = 1)
	s: search term
	o: 0 (default) for text-only or 1 for full options list
	text: selected text
	filterer_[filterer]: name of filterer field to be used to filter the drop-down contents
				must be one of the filteres defined for the concerned field
*/

	$start_ts = microtime(true);

	// how many results to return per call, in case of json output
	$results_per_page = 50;

	$curr_dir = dirname(__FILE__);
	include("$curr_dir/defaultLang.php");
	include("$curr_dir/language.php");
	include("$curr_dir/lib.php");

	handle_maintenance();

	// drop-downs config
	$lookups = array(   
		'redacteur' => array(   
			'badges' => array(
				'parent_table' => 'ref_badges',
				'parent_pk_field' => 'id_badge',
				'parent_caption' => 'IF(CHAR_LENGTH(`ref_badges`.`titre`) || CHAR_LENGTH(`ref_badges`.`icone_badge`), CONCAT_WS(\'\', `ref_badges`.`titre`, `ref_badges`.`icone_badge`), \'\')',
				'parent_from' => '`ref_badges` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			)
		),
		'Dossier_histoire' => array(   
			'auteur' => array(
				'parent_table' => 'redacteur',
				'parent_pk_field' => 'id_redact',
				'parent_caption' => 'IF(CHAR_LENGTH(`redacteur`.`prenom`) || CHAR_LENGTH(`redacteur`.`nom`), CONCAT_WS(\'\', `redacteur`.`prenom`, \' \', `redacteur`.`nom`), \'\')',
				'parent_from' => '`redacteur` LEFT JOIN `ref_badges` as ref_badges1 ON `ref_badges1`.`id_badge`=`redacteur`.`badges` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			)
		),
		'chapitre' => array(   
			'Mission' => array(
				'parent_table' => 'ref_mission',
				'parent_pk_field' => 'id_misref',
				'parent_caption' => 'IF(CHAR_LENGTH(`ref_mission`.`titre`) || CHAR_LENGTH(`ref_mission`.`description`), CONCAT_WS(\'\', `ref_mission`.`titre`, \' : \', `ref_mission`.`description`), \'\')',
				'parent_from' => '`ref_mission` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'rattache_a_dossier' => array(
				'parent_table' => 'Dossier_histoire',
				'parent_pk_field' => 'id2dossier',
				'parent_caption' => '`Dossier_histoire`.`titre_histoire`',
				'parent_from' => '`Dossier_histoire` LEFT JOIN `redacteur` as redacteur1 ON `redacteur1`.`id_redact`=`Dossier_histoire`.`auteur` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			)
		),
		'sequence' => array(   
			'rattache_a_chapitre' => array(
				'parent_table' => 'chapitre',
				'parent_pk_field' => 'id',
				'parent_caption' => '`chapitre`.`titre`',
				'parent_from' => '`chapitre` LEFT JOIN `ref_mission` as ref_mission1 ON `ref_mission1`.`id_misref`=`chapitre`.`Mission` LEFT JOIN `Dossier_histoire` as Dossier_histoire1 ON `Dossier_histoire1`.`id2dossier`=`chapitre`.`rattache_a_dossier` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'modele' => array(
				'parent_table' => 'ref_sequences',
				'parent_pk_field' => 'id_seqref',
				'parent_caption' => 'IF(CHAR_LENGTH(`ref_sequences`.`typologie`) || CHAR_LENGTH(`ref_sequences`.`titre`), CONCAT_WS(\'\', `ref_sequences`.`typologie`, \' : \', `ref_sequences`.`titre`), \'\')',
				'parent_from' => '`ref_sequences` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			)
		),
		'Objectifs' => array(   
			'rattache_a_dos2j' => array(
				'parent_table' => 'Dossier_histoire',
				'parent_pk_field' => 'id2dossier',
				'parent_caption' => '`Dossier_histoire`.`titre_histoire`',
				'parent_from' => '`Dossier_histoire` LEFT JOIN `redacteur` as redacteur1 ON `redacteur1`.`id_redact`=`Dossier_histoire`.`auteur` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			)
		),
		'moyens' => array(   
			'rattache_a_dos2j' => array(
				'parent_table' => 'Dossier_histoire',
				'parent_pk_field' => 'id2dossier',
				'parent_caption' => '`Dossier_histoire`.`titre_histoire`',
				'parent_from' => '`Dossier_histoire` LEFT JOIN `redacteur` as redacteur1 ON `redacteur1`.`id_redact`=`Dossier_histoire`.`auteur` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			)
		),
		'Objets' => array(   
			'Contient' => array(
				'parent_table' => 'Objets',
				'parent_pk_field' => 'id_objet',
				'parent_caption' => 'IF(CHAR_LENGTH(`Objets`.`nom_objet`) || CHAR_LENGTH(`Objets`.`illustration`), CONCAT_WS(\'\', `Objets`.`nom_objet`, `Objets`.`illustration`), \'\')',
				'parent_from' => '`Objets` LEFT JOIN `Objets` as Objets1 ON `Objets1`.`id_objet`=`Objets`.`Contient` LEFT JOIN `Dossier_histoire` as Dossier_histoire1 ON `Dossier_histoire1`.`id2dossier`=`Objets`.`rattache_a_dos2j` LEFT JOIN `sequence` as sequence1 ON `sequence1`.`id_sequence`=`Objets`.`rattache_a_seq` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => true,
				'list_type' => 0,
				'not_null' => false
			),
			'rattache_a_dos2j' => array(
				'parent_table' => 'Dossier_histoire',
				'parent_pk_field' => 'id2dossier',
				'parent_caption' => '`Dossier_histoire`.`titre_histoire`',
				'parent_from' => '`Dossier_histoire` LEFT JOIN `redacteur` as redacteur1 ON `redacteur1`.`id_redact`=`Dossier_histoire`.`auteur` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'rattache_a_seq' => array(
				'parent_table' => 'sequence',
				'parent_pk_field' => 'id_sequence',
				'parent_caption' => 'IF(CHAR_LENGTH(`sequence`.`numero_ordre`) || CHAR_LENGTH(`sequence`.`titre`), CONCAT_WS(\'\', `sequence`.`numero_ordre`, \' \', `sequence`.`titre`), \'\')',
				'parent_from' => '`sequence` LEFT JOIN `chapitre` as chapitre1 ON `chapitre1`.`id`=`sequence`.`rattache_a_chapitre` LEFT JOIN `ref_sequences` as ref_sequences1 ON `ref_sequences1`.`id_seqref`=`sequence`.`modele` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			)
		),
		'personnages' => array(   
			'quepossedetil' => array(
				'parent_table' => 'Objets',
				'parent_pk_field' => 'id_objet',
				'parent_caption' => 'IF(CHAR_LENGTH(`Objets`.`nom_objet`) || CHAR_LENGTH(`Objets`.`illustration`), CONCAT_WS(\'\', `Objets`.`nom_objet`, `Objets`.`illustration`), \'\')',
				'parent_from' => '`Objets` LEFT JOIN `Objets` as Objets1 ON `Objets1`.`id_objet`=`Objets`.`Contient` LEFT JOIN `Dossier_histoire` as Dossier_histoire1 ON `Dossier_histoire1`.`id2dossier`=`Objets`.`rattache_a_dos2j` LEFT JOIN `sequence` as sequence1 ON `sequence1`.`id_sequence`=`Objets`.`rattache_a_seq` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'rattache_a_dos2j' => array(
				'parent_table' => 'Dossier_histoire',
				'parent_pk_field' => 'id2dossier',
				'parent_caption' => '`Dossier_histoire`.`titre_histoire`',
				'parent_from' => '`Dossier_histoire` LEFT JOIN `redacteur` as redacteur1 ON `redacteur1`.`id_redact`=`Dossier_histoire`.`auteur` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'rattache_a_seq' => array(
				'parent_table' => 'sequence',
				'parent_pk_field' => 'id_sequence',
				'parent_caption' => 'IF(CHAR_LENGTH(`sequence`.`numero_ordre`) || CHAR_LENGTH(`sequence`.`titre`), CONCAT_WS(\'\', `sequence`.`numero_ordre`, \' \', `sequence`.`titre`), \'\')',
				'parent_from' => '`sequence` LEFT JOIN `chapitre` as chapitre1 ON `chapitre1`.`id`=`sequence`.`rattache_a_chapitre` LEFT JOIN `ref_sequences` as ref_sequences1 ON `ref_sequences1`.`id_seqref`=`sequence`.`modele` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			)
		),
		'lieu_et_scene' => array(   
			'objet_present' => array(
				'parent_table' => 'Objets',
				'parent_pk_field' => 'id_objet',
				'parent_caption' => 'IF(CHAR_LENGTH(`Objets`.`nom_objet`) || CHAR_LENGTH(`Objets`.`illustration`), CONCAT_WS(\'\', `Objets`.`nom_objet`, `Objets`.`illustration`), \'\')',
				'parent_from' => '`Objets` LEFT JOIN `Objets` as Objets1 ON `Objets1`.`id_objet`=`Objets`.`Contient` LEFT JOIN `Dossier_histoire` as Dossier_histoire1 ON `Dossier_histoire1`.`id2dossier`=`Objets`.`rattache_a_dos2j` LEFT JOIN `sequence` as sequence1 ON `sequence1`.`id_sequence`=`Objets`.`rattache_a_seq` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'persos_present' => array(
				'parent_table' => 'personnages',
				'parent_pk_field' => 'id_perso',
				'parent_caption' => 'IF(CHAR_LENGTH(`personnages`.`nom`) || CHAR_LENGTH(`personnages`.`illustration`), CONCAT_WS(\'\', `personnages`.`nom`, `personnages`.`illustration`), \'\')',
				'parent_from' => '`personnages` LEFT JOIN `Objets` as Objets1 ON `Objets1`.`id_objet`=`personnages`.`quepossedetil` LEFT JOIN `Dossier_histoire` as Dossier_histoire1 ON `Dossier_histoire1`.`id2dossier`=`personnages`.`rattache_a_dos2j` LEFT JOIN `sequence` as sequence1 ON `sequence1`.`id_sequence`=`personnages`.`rattache_a_seq` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'rattache_a_dos2j' => array(
				'parent_table' => 'Dossier_histoire',
				'parent_pk_field' => 'id2dossier',
				'parent_caption' => '`Dossier_histoire`.`titre_histoire`',
				'parent_from' => '`Dossier_histoire` LEFT JOIN `redacteur` as redacteur1 ON `redacteur1`.`id_redact`=`Dossier_histoire`.`auteur` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'rattache_a_seq' => array(
				'parent_table' => 'sequence',
				'parent_pk_field' => 'id_sequence',
				'parent_caption' => 'IF(CHAR_LENGTH(`sequence`.`numero_ordre`) || CHAR_LENGTH(`sequence`.`titre`), CONCAT_WS(\'\', `sequence`.`numero_ordre`, \' \', `sequence`.`titre`), \'\')',
				'parent_from' => '`sequence` LEFT JOIN `chapitre` as chapitre1 ON `chapitre1`.`id`=`sequence`.`rattache_a_chapitre` LEFT JOIN `ref_sequences` as ref_sequences1 ON `ref_sequences1`.`id_seqref`=`sequence`.`modele` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			)
		),
		'ref_badges' => array(  
		),
		'ref_sequences' => array(  
		),
		'ref_mission' => array(  
		),
		'boiteaid' => array(  
		),
		'ref_capteur' => array(  
		)
	);

	// XSS prevention
	$xss = new CI_Input();
	$xss->charset = datalist_db_encoding;

	// receive and verify user input
	$table_name = $_REQUEST['t'];
	$field_name = $_REQUEST['f'];
	$search_id = makeSafe(from_utf8($_REQUEST['id']));
	$selected_text = from_utf8($_REQUEST['text']);
	$returnOptions = ($_REQUEST['o'] == 1 ? true : false);
	$page = intval($_REQUEST['p']);
	if($page < 1)  $page = 1;
	$skip = $results_per_page * ($page - 1);
	$search_term = makeSafe(from_utf8($_REQUEST['s']));

	if(!isset($lookups[$table_name][$field_name])) die('{ "error": "Invalid table or field." }');

	// can user access the requested table?
	$perm = getTablePermissions($table_name);
	if(!$perm[0] && !$search_id) die('{ "error": "' . addslashes($Translation['tableAccessDenied']) . '" }');

	$field = $lookups[$table_name][$field_name];

	$wheres = array();

	// search term provided?
	if($search_term){
		$wheres[] = "{$field['parent_caption']} like '%{$search_term}%'";
	}

	// any filterers specified?
	if(is_array($field['filterers'])){
		foreach($field['filterers'] as $filterer => $filterer_parent){
			$get = (isset($_REQUEST["filterer_{$filterer}"]) ? $_REQUEST["filterer_{$filterer}"] : false);
			if($get){
				$wheres[] = "`{$field['parent_table']}`.`$filterer_parent`='" . makeSafe($get) . "'";
			}
		}
	}

	// inherit permissions?
	if($field['inherit_permissions']){
		$inherit = permissions_sql($field['parent_table']);
		if($inherit === false && !$search_id) die($Translation['tableAccessDenied']);

		if($inherit['where']) $wheres[] = $inherit['where'];
		if($inherit['from']) $field['parent_from'] .= ", {$inherit['from']}";
	}

	// single value?
	if($field['list_type'] != 2 && $search_id){
		$wheres[] = "`{$field['parent_table']}`.`{$field['parent_pk_field']}`='{$search_id}'";
	}

	if(count($wheres)){
		$where = 'WHERE ' . implode(' AND ', $wheres);
	}

	// define the combo and return the code
	$combo = new DataCombo;
	if($field['custom_query']){
		$qm = array(); $custom_where = ''; $custom_order_by = '2';
		$combo->Query = $field['custom_query'];

		if(preg_match('/ order by (.*)$/i', $combo->Query, $qm)){
			$custom_order_by = $qm[1];
			$combo->Query = preg_replace('/ order by .*$/i', '', $combo->Query);
		}

		if(preg_match('/ where (.*)$/i', $combo->Query, $qm)){
			$custom_where = $qm[1];
			$combo->Query = preg_replace('/ where .*$/i', '', $combo->Query);
		}

		if($where && $custom_where){
			$combo->Query .=  " {$where} AND ({$custom_where}) ORDER BY {$custom_order_by}";
		}elseif($custom_where){
			$combo->Query .=  " WHERE {$custom_where} ORDER BY {$custom_order_by}";
		}else{
			$combo->Query .=  " {$where} ORDER BY {$custom_order_by}";
		}

		$query_match = array();
		preg_match('/select (.*) from (.*)$/i', $combo->Query, $query_match);

		if(isset($query_match[2])){
			$count_query = "SELECT count(1) FROM {$query_match[2]}";
		}else{
			$count_query = '';
		}
	}else{
		$combo->Query = "SELECT " . ($field['inherit_permissions'] ? 'DISTINCT ' : '') . "`{$field['parent_table']}`.`{$field['parent_pk_field']}`, {$field['parent_caption']} FROM {$field['parent_from']} {$where} ORDER BY 2";
		$count_query = "SELECT count(1) FROM {$field['parent_from']} {$where}";
	}
	$combo->table = $table_name;
	$combo->parent_table = $field['parent_table'];
	$combo->SelectName = $field_name;
	$combo->ListType = $field['list_type'];
	if($search_id){
		$combo->SelectedData = $search_id;
	}elseif($selected_text){
		$combo->SelectedData = getValueGivenCaption($combo->Query, $selected_text);
	}

	if($field['list_type'] == 2){
		$combo->Render();
		$combo->HTML = str_replace('<select ', '<select onchange="' . $field_name . '_changed();" ', $combo->HTML);

		// return response
		if($returnOptions){
			?><span id="<?php echo $field_name; ?>-combo-list"><?php echo $combo->HTML; ?></span><?php
		}else{
			?>
				<span id="<?php echo $field_name; ?>-match-text"><?php echo $combo->MatchText; ?></span>
				<input type="hidden" id="<?php echo $field_name; ?>" value="<?php echo html_attr($combo->SelectedData); ?>" />
			<?php
		}
	}else{
		/* return json */
		header('Content-type: application/json');

		if(!preg_match('/ limit .+/i', $combo->Query)){
			if(!$search_id) $combo->Query .= " LIMIT {$skip}, {$results_per_page}";
			if($search_id) $combo->Query .= " LIMIT 1";
		}

		$prepared_data = array();

		// specific caption provided and list_type is not radio?
		if(!$search_id && $selected_text){
			$search_id = getValueGivenCaption($combo->Query, $selected_text);
			if($search_id) $prepared_data[] = array('id' => to_utf8($search_id), 'text' => to_utf8($xss->xss_clean($selected_text)));
		}else{
			$res = sql($combo->Query, $eo);
			while($row = db_fetch_row($res)){
				if(empty($prepared_data) && $page == 1 && !$search_id && !$field['not_null']){
					$prepared_data[] = array('id' => empty_lookup_value, 'text' => to_utf8("<{$Translation['none']}>"));
				}

				$prepared_data[] = array('id' => to_utf8($row[0]), 'text' => to_utf8($xss->xss_clean($row[1])));
			}
		}

		if(empty($prepared_data)){ $prepared_data[] = array('id' => '', 'text' => to_utf8($Translation['No matches found!'])); }

		echo json_encode(array(
			'results' => $prepared_data,
			'more' => (@db_num_rows($res) >= $results_per_page),
			'elapsed' => round(microtime(true) - $start_ts, 3)
		));
	}

