<?php

// Data functions (insert, update, delete, form) for table Dossier_histoire

// This script and data application were generated by AppGini 5.61
// Download AppGini for free from https://bigprof.com/appgini/download/

function Dossier_histoire_insert(){
	global $Translation;

	// mm: can member insert record?
	$arrPerm=getTablePermissions('Dossier_histoire');
	if(!$arrPerm[1]){
		return false;
	}

	$data['titre_histoire'] = makeSafe($_REQUEST['titre_histoire']);
		if($data['titre_histoire'] == empty_lookup_value){ $data['titre_histoire'] = ''; }
	$data['resume'] = makeSafe($_REQUEST['resume']);
		if($data['resume'] == empty_lookup_value){ $data['resume'] = ''; }
	$data['creer_par'] = parseCode('<%%creatorUsername%%>', true);
	if($data['titre_histoire']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Titre de l\'histoire': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['resume'] == '') $data['resume'] = "C\'est l\'histoire de  ...";
	if($data['resume']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Resume': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}

	// hook: Dossier_histoire_before_insert
	if(function_exists('Dossier_histoire_before_insert')){
		$args=array();
		if(!Dossier_histoire_before_insert($data, getMemberInfo(), $args)){ return false; }
	}

	$o = array('silentErrors' => true);
	sql('insert into `Dossier_histoire` set       `titre_histoire`=' . (($data['titre_histoire'] !== '' && $data['titre_histoire'] !== NULL) ? "'{$data['titre_histoire']}'" : 'NULL') . ', `resume`=' . (($data['resume'] !== '' && $data['resume'] !== NULL) ? "'{$data['resume']}'" : 'NULL') . ', `creer_par`=' . "'{$data['creer_par']}'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo "<a href=\"Dossier_histoire_view.php?addNew_x=1\">{$Translation['< back']}</a>";
		exit;
	}

	$recID = db_insert_id(db_link());

	// automatic auteur
	if($_REQUEST['filterer_auteur']){
		sql("update `Dossier_histoire` set `auteur`='" . makeSafe($_REQUEST['filterer_auteur']) . "' where `id2dossier`='" . makeSafe($recID, false) . "'", $eo);
	}

	// hook: Dossier_histoire_after_insert
	if(function_exists('Dossier_histoire_after_insert')){
		$res = sql("select * from `Dossier_histoire` where `id2dossier`='" . makeSafe($recID, false) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=array();
		if(!Dossier_histoire_after_insert($data, getMemberInfo(), $args)){ return $recID; }
	}

	// mm: save ownership data
	sql("insert ignore into membership_userrecords set tableName='Dossier_histoire', pkValue='" . makeSafe($recID, false) . "', memberID='" . makeSafe(getLoggedMemberID(), false) . "', dateAdded='" . time() . "', dateUpdated='" . time() . "', groupID='" . getLoggedGroupID() . "'", $eo);

	return $recID;
}

function Dossier_histoire_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false){
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('Dossier_histoire');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='Dossier_histoire' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='Dossier_histoire' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: Dossier_histoire_before_delete
	if(function_exists('Dossier_histoire_before_delete')){
		$args=array();
		if(!Dossier_histoire_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	// child table: chapitre
	$res = sql("select `id2dossier` from `Dossier_histoire` where `id2dossier`='$selected_id'", $eo);
	$id2dossier = db_fetch_row($res);
	$rires = sql("select count(1) from `chapitre` where `rattache_a_dossier`='".addslashes($id2dossier[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "chapitre", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "chapitre", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='Dossier_histoire_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='Dossier_histoire_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	// child table: Objectifs
	$res = sql("select `id2dossier` from `Dossier_histoire` where `id2dossier`='$selected_id'", $eo);
	$id2dossier = db_fetch_row($res);
	$rires = sql("select count(1) from `Objectifs` where `rattache_a_dos2j`='".addslashes($id2dossier[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "Objectifs", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "Objectifs", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='Dossier_histoire_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='Dossier_histoire_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	// child table: moyens
	$res = sql("select `id2dossier` from `Dossier_histoire` where `id2dossier`='$selected_id'", $eo);
	$id2dossier = db_fetch_row($res);
	$rires = sql("select count(1) from `moyens` where `rattache_a_dos2j`='".addslashes($id2dossier[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "moyens", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "moyens", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='Dossier_histoire_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='Dossier_histoire_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	// child table: Objets
	$res = sql("select `id2dossier` from `Dossier_histoire` where `id2dossier`='$selected_id'", $eo);
	$id2dossier = db_fetch_row($res);
	$rires = sql("select count(1) from `Objets` where `rattache_a_dos2j`='".addslashes($id2dossier[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "Objets", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "Objets", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='Dossier_histoire_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='Dossier_histoire_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	// child table: personnages
	$res = sql("select `id2dossier` from `Dossier_histoire` where `id2dossier`='$selected_id'", $eo);
	$id2dossier = db_fetch_row($res);
	$rires = sql("select count(1) from `personnages` where `rattache_a_dos2j`='".addslashes($id2dossier[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "personnages", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "personnages", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='Dossier_histoire_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='Dossier_histoire_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	// child table: lieu_et_scene
	$res = sql("select `id2dossier` from `Dossier_histoire` where `id2dossier`='$selected_id'", $eo);
	$id2dossier = db_fetch_row($res);
	$rires = sql("select count(1) from `lieu_et_scene` where `rattache_a_dos2j`='".addslashes($id2dossier[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "lieu_et_scene", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "lieu_et_scene", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='Dossier_histoire_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='Dossier_histoire_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	sql("delete from `Dossier_histoire` where `id2dossier`='$selected_id'", $eo);

	// hook: Dossier_histoire_after_delete
	if(function_exists('Dossier_histoire_after_delete')){
		$args=array();
		Dossier_histoire_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='Dossier_histoire' and pkValue='$selected_id'", $eo);
}

function Dossier_histoire_update($selected_id){
	global $Translation;

	// mm: can member edit record?
	$arrPerm=getTablePermissions('Dossier_histoire');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='Dossier_histoire' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='Dossier_histoire' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['titre_histoire'] = makeSafe($_REQUEST['titre_histoire']);
		if($data['titre_histoire'] == empty_lookup_value){ $data['titre_histoire'] = ''; }
	if($data['titre_histoire']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Titre de l\'histoire': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['resume'] = makeSafe($_REQUEST['resume']);
		if($data['resume'] == empty_lookup_value){ $data['resume'] = ''; }
	if($data['resume']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Resume': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['selectedID']=makeSafe($selected_id);

	// hook: Dossier_histoire_before_update
	if(function_exists('Dossier_histoire_before_update')){
		$args=array();
		if(!Dossier_histoire_before_update($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('update `Dossier_histoire` set       `titre_histoire`=' . (($data['titre_histoire'] !== '' && $data['titre_histoire'] !== NULL) ? "'{$data['titre_histoire']}'" : 'NULL') . ', `resume`=' . (($data['resume'] !== '' && $data['resume'] !== NULL) ? "'{$data['resume']}'" : 'NULL') . " where `id2dossier`='".makeSafe($selected_id)."'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo '<a href="Dossier_histoire_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: Dossier_histoire_after_update
	if(function_exists('Dossier_histoire_after_update')){
		$res = sql("SELECT * FROM `Dossier_histoire` WHERE `id2dossier`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['id2dossier'];
		$args = array();
		if(!Dossier_histoire_after_update($data, getMemberInfo(), $args)){ return; }
	}

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."' where tableName='Dossier_histoire' and pkValue='".makeSafe($selected_id)."'", $eo);

}

function Dossier_histoire_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0, $TemplateDV = '', $TemplateDVP = ''){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('Dossier_histoire');
	if(!$arrPerm[1] && $selected_id==''){ return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != ''){
		$dvprint = true;
	}

	$filterer_auteur = thisOr(undo_magic_quotes($_REQUEST['filterer_auteur']), '');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: auteur
	$combo_auteur = new DataCombo;

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='Dossier_histoire' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='Dossier_histoire' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("select * from `Dossier_histoire` where `id2dossier`='".makeSafe($selected_id)."'", $eo);
		if(!($row = db_fetch_array($res))){
			return error_message($Translation['No records found'], 'Dossier_histoire_view.php', false);
		}
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
		$combo_auteur->SelectedData = $row['auteur'];
	}else{
		$combo_auteur->SelectedData = $filterer_auteur;
	}
	$combo_auteur->HTML = '<span id="auteur-container' . $rnd1 . '"></span><input type="hidden" name="auteur" id="auteur' . $rnd1 . '" value="' . html_attr($combo_auteur->SelectedData) . '">';
	$combo_auteur->MatchText = '<span id="auteur-container-readonly' . $rnd1 . '"></span><input type="hidden" name="auteur" id="auteur' . $rnd1 . '" value="' . html_attr($combo_auteur->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_auteur__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['auteur'] : $filterer_auteur); ?>"};

		jQuery(function() {
			setTimeout(function(){
				if(typeof(auteur_reload__RAND__) == 'function') auteur_reload__RAND__();
			}, 10); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function auteur_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			$j("#auteur-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_auteur__RAND__.value, t: 'Dossier_histoire', f: 'auteur' },
						success: function(resp){
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="auteur"]').val(resp.results[0].id);
							$j('[id=auteur-container-readonly__RAND__]').html('<span id="auteur-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=redacteur_view_parent]').hide(); }else{ $j('.btn[id=redacteur_view_parent]').show(); }


							if(typeof(auteur_update_autofills__RAND__) == 'function') auteur_update_autofills__RAND__();
						}
					});
				},
				width: ($j('fieldset .col-xs-11').width() - select2_max_width_decrement()) + 'px',
				formatNoMatches: function(term){ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ return { s: term, p: page, t: 'Dossier_histoire', f: 'auteur' }; },
					results: function(resp, page){ return resp; }
				},
				escapeMarkup: function(str){ return str; }
			}).on('change', function(e){
				AppGini.current_auteur__RAND__.value = e.added.id;
				AppGini.current_auteur__RAND__.text = e.added.text;
				$j('[name="auteur"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=redacteur_view_parent]').hide(); }else{ $j('.btn[id=redacteur_view_parent]').show(); }


				if(typeof(auteur_update_autofills__RAND__) == 'function') auteur_update_autofills__RAND__();
			});

			if(!$j("#auteur-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_auteur__RAND__.value, t: 'Dossier_histoire', f: 'auteur' },
					success: function(resp){
						$j('[name="auteur"]').val(resp.results[0].id);
						$j('[id=auteur-container-readonly__RAND__]').html('<span id="auteur-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=redacteur_view_parent]').hide(); }else{ $j('.btn[id=redacteur_view_parent]').show(); }

						if(typeof(auteur_update_autofills__RAND__) == 'function') auteur_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_auteur__RAND__.value, t: 'Dossier_histoire', f: 'auteur' },
				success: function(resp){
					$j('[id=auteur-container__RAND__], [id=auteur-container-readonly__RAND__]').html('<span id="auteur-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=redacteur_view_parent]').hide(); }else{ $j('.btn[id=redacteur_view_parent]').show(); }

					if(typeof(auteur_update_autofills__RAND__) == 'function') auteur_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	if($dvprint){
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/Dossier_histoire_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	}else{
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/Dossier_histoire_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Dossier2jeu details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert){
		if(!$selected_id) $templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return Dossier_histoire_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return Dossier_histoire_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']){
		$backAction = 'window.parent.jQuery(\'.modal\').modal(\'hide\'); return false;';
	}else{
		$backAction = '$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id){
		if(!$_REQUEST['Embedded']) $templateCode=str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate){
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return Dossier_histoire_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)){
		$jsReadOnly .= "\tjQuery('#titre_histoire').replaceWith('<div class=\"form-control-static\" id=\"titre_histoire\">' + (jQuery('#titre_histoire').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	}elseif($AllowInsert){
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode=str_replace('<%%COMBO(auteur)%%>', $combo_auteur->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(auteur)%%>', $combo_auteur->MatchText, $templateCode);
	$templateCode=str_replace('<%%URLCOMBOTEXT(auteur)%%>', urlencode($combo_auteur->MatchText), $templateCode);

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array(  'auteur' => array('redacteur', 'Auteur'));
	foreach($lookup_fields as $luf => $ptfc){
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']){
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] && !$_REQUEST['Embedded']){
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode=str_replace('<%%UPLOADFILE(id2dossier)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(auteur)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(titre_histoire)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(resume)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(creer_par)%%>', '', $templateCode);

	// process values
	if($selected_id){
		$templateCode=str_replace('<%%VALUE(id2dossier)%%>', html_attr($row['id2dossier']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(id2dossier)%%>', urlencode($urow['id2dossier']), $templateCode);
		$templateCode=str_replace('<%%VALUE(auteur)%%>', html_attr($row['auteur']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(auteur)%%>', urlencode($urow['auteur']), $templateCode);
		$templateCode=str_replace('<%%VALUE(titre_histoire)%%>', html_attr($row['titre_histoire']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(titre_histoire)%%>', urlencode($urow['titre_histoire']), $templateCode);
		if($AllowUpdate || $AllowInsert){
			$templateCode = str_replace('<%%HTMLAREA(resume)%%>', '<textarea name="resume" id="resume" rows="5">' . html_attr($row['resume']) . '</textarea>', $templateCode);
		}else{
			$templateCode = str_replace('<%%HTMLAREA(resume)%%>', '<div id="resume" class="form-control-static">' . $row['resume'] . '</div>', $templateCode);
		}
		$templateCode=str_replace('<%%VALUE(resume)%%>', nl2br($row['resume']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(resume)%%>', urlencode($urow['resume']), $templateCode);
		$templateCode=str_replace('<%%VALUE(creer_par)%%>', html_attr($row['creer_par']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(creer_par)%%>', urlencode($urow['creer_par']), $templateCode);
	}else{
		$templateCode=str_replace('<%%VALUE(id2dossier)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(id2dossier)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(auteur)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(auteur)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(titre_histoire)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(titre_histoire)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%HTMLAREA(resume)%%>', '<textarea name="resume" id="resume" rows="5">C\'est l\'histoire de  ...</textarea>', $templateCode);
		$templateCode=str_replace('<%%VALUE(creer_par)%%>', '<%%creatorUsername%%>', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(creer_par)%%>', urlencode('<%%creatorUsername%%>'), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode=str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode=str_replace('<%%', '<!-- ', $templateCode);
	$templateCode=str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == ''){
		$templateCode .= "\n\n<script>\$j(function(){\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption){
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id){
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	if( $_REQUEST['FilterField'][1]=='2' && $_REQUEST['FilterOperator'][1]=='<=>'){
		$templateCode.="\n<input type=hidden name=auteur value=\"" . html_attr((get_magic_quotes_gpc() ? stripslashes($_REQUEST['FilterValue'][1]) : $_REQUEST['FilterValue'][1]))."\">\n";
	}

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('Dossier_histoire');
	if($selected_id){
		$jdata = get_joined_record('Dossier_histoire', $selected_id);
		$rdata = $row;
	}
	$cache_data = array(
		'rdata' => array_map('nl2br', array_map('addslashes', $rdata)),
		'jdata' => array_map('nl2br', array_map('addslashes', $jdata)),
	);
	$templateCode .= loadView('Dossier_histoire-ajax-cache', $cache_data);

	// hook: Dossier_histoire_dv
	if(function_exists('Dossier_histoire_dv')){
		$args=array();
		Dossier_histoire_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>