<?php

// Data functions (insert, update, delete, form) for table lieu_et_scene

// This script and data application were generated by AppGini 5.75
// Download AppGini for free from https://bigprof.com/appgini/download/

function lieu_et_scene_insert(){
	global $Translation;

	// mm: can member insert record?
	$arrPerm=getTablePermissions('lieu_et_scene');
	if(!$arrPerm[1]){
		return false;
	}

	$data['nom_du_lieu'] = br2nl(makeSafe($_REQUEST['nom_du_lieu']));
	$data['description'] = makeSafe($_REQUEST['description']);
		if($data['description'] == empty_lookup_value){ $data['description'] = ''; }
	$data['difficulte_nivo'] = makeSafe($_REQUEST['difficulte_nivo']);
		if($data['difficulte_nivo'] == empty_lookup_value){ $data['difficulte_nivo'] = ''; }
	$data['condition_entree'] = makeSafe($_REQUEST['condition_entree']);
		if($data['condition_entree'] == empty_lookup_value){ $data['condition_entree'] = ''; }
	$data['condition_sortie'] = makeSafe($_REQUEST['condition_sortie']);
		if($data['condition_sortie'] == empty_lookup_value){ $data['condition_sortie'] = ''; }
	$data['objet_present'] = makeSafe($_REQUEST['objet_present']);
		if($data['objet_present'] == empty_lookup_value){ $data['objet_present'] = ''; }
	$data['persos_present'] = makeSafe($_REQUEST['persos_present']);
		if($data['persos_present'] == empty_lookup_value){ $data['persos_present'] = ''; }
	$data['creer_par'] = parseCode('<%%creatorUsername%%>', true);
	$data['rattache_a_dos2j'] = makeSafe($_REQUEST['rattache_a_dos2j']);
		if($data['rattache_a_dos2j'] == empty_lookup_value){ $data['rattache_a_dos2j'] = ''; }
	$data['rattache_a_seq'] = makeSafe($_REQUEST['rattache_a_seq']);
		if($data['rattache_a_seq'] == empty_lookup_value){ $data['rattache_a_seq'] = ''; }
	$data['illustration'] = PrepareUploadedFile('illustration', 102400,'jpg|jpeg|gif|png', false, '');
	if($data['illustration']) createThumbnail($data['illustration'], getThumbnailSpecs('lieu_et_scene', 'illustration', 'tv'));
	if($data['illustration']) createThumbnail($data['illustration'], getThumbnailSpecs('lieu_et_scene', 'illustration', 'dv'));
	if($data['nom_du_lieu']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Nom du lieu': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['condition_entree'] == '') $data['condition_entree'] = "Pour acc&#233;der &#224; cette sc&#232;ne...";
	if($data['condition_sortie'] == '') $data['condition_sortie'] = "Pour sortir de cette sc&#232;ne...";

	/* for empty upload fields, when saving a copy of an existing record, copy the original upload field */
	if($_REQUEST['SelectedID']){
		$res = sql("select * from lieu_et_scene where id_lets='" . makeSafe($_REQUEST['SelectedID']) . "'", $eo);
		if($row = db_fetch_assoc($res)){
			if(!$data['illustration']) $data['illustration'] = makeSafe($row['illustration']);
		}
	}

	// hook: lieu_et_scene_before_insert
	if(function_exists('lieu_et_scene_before_insert')){
		$args=array();
		if(!lieu_et_scene_before_insert($data, getMemberInfo(), $args)){ return false; }
	}

	$o = array('silentErrors' => true);
	sql('insert into `lieu_et_scene` set       `nom_du_lieu`=' . (($data['nom_du_lieu'] !== '' && $data['nom_du_lieu'] !== NULL) ? "'{$data['nom_du_lieu']}'" : 'NULL') . ', ' . ($data['illustration'] != '' ? "`illustration`='{$data['illustration']}'" : '`illustration`=NULL') . ', `description`=' . (($data['description'] !== '' && $data['description'] !== NULL) ? "'{$data['description']}'" : 'NULL') . ', `difficulte_nivo`=' . (($data['difficulte_nivo'] !== '' && $data['difficulte_nivo'] !== NULL) ? "'{$data['difficulte_nivo']}'" : 'NULL') . ', `condition_entree`=' . (($data['condition_entree'] !== '' && $data['condition_entree'] !== NULL) ? "'{$data['condition_entree']}'" : 'NULL') . ', `condition_sortie`=' . (($data['condition_sortie'] !== '' && $data['condition_sortie'] !== NULL) ? "'{$data['condition_sortie']}'" : 'NULL') . ', `objet_present`=' . (($data['objet_present'] !== '' && $data['objet_present'] !== NULL) ? "'{$data['objet_present']}'" : 'NULL') . ', `persos_present`=' . (($data['persos_present'] !== '' && $data['persos_present'] !== NULL) ? "'{$data['persos_present']}'" : 'NULL') . ', `creer_par`=' . "'{$data['creer_par']}'" . ', `rattache_a_dos2j`=' . (($data['rattache_a_dos2j'] !== '' && $data['rattache_a_dos2j'] !== NULL) ? "'{$data['rattache_a_dos2j']}'" : 'NULL') . ', `rattache_a_seq`=' . (($data['rattache_a_seq'] !== '' && $data['rattache_a_seq'] !== NULL) ? "'{$data['rattache_a_seq']}'" : 'NULL'), $o);
	if($o['error']!=''){
		echo $o['error'];
		echo "<a href=\"lieu_et_scene_view.php?addNew_x=1\">{$Translation['< back']}</a>";
		exit;
	}

	$recID = db_insert_id(db_link());

	// hook: lieu_et_scene_after_insert
	if(function_exists('lieu_et_scene_after_insert')){
		$res = sql("select * from `lieu_et_scene` where `id_lets`='" . makeSafe($recID, false) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=array();
		if(!lieu_et_scene_after_insert($data, getMemberInfo(), $args)){ return $recID; }
	}

	// mm: save ownership data
	set_record_owner('lieu_et_scene', $recID, getLoggedMemberID());

	return $recID;
}

function lieu_et_scene_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false){
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('lieu_et_scene');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='lieu_et_scene' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='lieu_et_scene' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: lieu_et_scene_before_delete
	if(function_exists('lieu_et_scene_before_delete')){
		$args=array();
		if(!lieu_et_scene_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	sql("delete from `lieu_et_scene` where `id_lets`='$selected_id'", $eo);

	// hook: lieu_et_scene_after_delete
	if(function_exists('lieu_et_scene_after_delete')){
		$args=array();
		lieu_et_scene_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='lieu_et_scene' and pkValue='$selected_id'", $eo);
}

function lieu_et_scene_update($selected_id){
	global $Translation;

	// mm: can member edit record?
	$arrPerm=getTablePermissions('lieu_et_scene');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='lieu_et_scene' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='lieu_et_scene' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['nom_du_lieu'] = br2nl(makeSafe($_REQUEST['nom_du_lieu']));
	if($data['nom_du_lieu']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Nom du lieu': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['description'] = makeSafe($_REQUEST['description']);
		if($data['description'] == empty_lookup_value){ $data['description'] = ''; }
	$data['difficulte_nivo'] = makeSafe($_REQUEST['difficulte_nivo']);
		if($data['difficulte_nivo'] == empty_lookup_value){ $data['difficulte_nivo'] = ''; }
	$data['condition_entree'] = makeSafe($_REQUEST['condition_entree']);
		if($data['condition_entree'] == empty_lookup_value){ $data['condition_entree'] = ''; }
	$data['condition_sortie'] = makeSafe($_REQUEST['condition_sortie']);
		if($data['condition_sortie'] == empty_lookup_value){ $data['condition_sortie'] = ''; }
	$data['objet_present'] = makeSafe($_REQUEST['objet_present']);
		if($data['objet_present'] == empty_lookup_value){ $data['objet_present'] = ''; }
	$data['persos_present'] = makeSafe($_REQUEST['persos_present']);
		if($data['persos_present'] == empty_lookup_value){ $data['persos_present'] = ''; }
	$data['rattache_a_dos2j'] = makeSafe($_REQUEST['rattache_a_dos2j']);
		if($data['rattache_a_dos2j'] == empty_lookup_value){ $data['rattache_a_dos2j'] = ''; }
	$data['rattache_a_seq'] = makeSafe($_REQUEST['rattache_a_seq']);
		if($data['rattache_a_seq'] == empty_lookup_value){ $data['rattache_a_seq'] = ''; }
	$data['selectedID']=makeSafe($selected_id);
	if($_REQUEST['illustration_remove'] == 1){
		$data['illustration'] = '';
	}else{
		$data['illustration'] = PrepareUploadedFile('illustration', 102400, 'jpg|jpeg|gif|png', false, "");
		if($data['illustration']) createThumbnail($data['illustration'], getThumbnailSpecs('lieu_et_scene', 'illustration', 'tv'));
		if($data['illustration']) createThumbnail($data['illustration'], getThumbnailSpecs('lieu_et_scene', 'illustration', 'dv'));
	}

	// hook: lieu_et_scene_before_update
	if(function_exists('lieu_et_scene_before_update')){
		$args=array();
		if(!lieu_et_scene_before_update($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('update `lieu_et_scene` set       `nom_du_lieu`=' . (($data['nom_du_lieu'] !== '' && $data['nom_du_lieu'] !== NULL) ? "'{$data['nom_du_lieu']}'" : 'NULL') . ', ' . ($data['illustration']!='' ? "`illustration`='{$data['illustration']}'" : ($_REQUEST['illustration_remove'] != 1 ? '`illustration`=`illustration`' : '`illustration`=NULL')) . ', `description`=' . (($data['description'] !== '' && $data['description'] !== NULL) ? "'{$data['description']}'" : 'NULL') . ', `difficulte_nivo`=' . (($data['difficulte_nivo'] !== '' && $data['difficulte_nivo'] !== NULL) ? "'{$data['difficulte_nivo']}'" : 'NULL') . ', `condition_entree`=' . (($data['condition_entree'] !== '' && $data['condition_entree'] !== NULL) ? "'{$data['condition_entree']}'" : 'NULL') . ', `condition_sortie`=' . (($data['condition_sortie'] !== '' && $data['condition_sortie'] !== NULL) ? "'{$data['condition_sortie']}'" : 'NULL') . ', `objet_present`=' . (($data['objet_present'] !== '' && $data['objet_present'] !== NULL) ? "'{$data['objet_present']}'" : 'NULL') . ', `persos_present`=' . (($data['persos_present'] !== '' && $data['persos_present'] !== NULL) ? "'{$data['persos_present']}'" : 'NULL') . ', `rattache_a_dos2j`=' . (($data['rattache_a_dos2j'] !== '' && $data['rattache_a_dos2j'] !== NULL) ? "'{$data['rattache_a_dos2j']}'" : 'NULL') . ', `rattache_a_seq`=' . (($data['rattache_a_seq'] !== '' && $data['rattache_a_seq'] !== NULL) ? "'{$data['rattache_a_seq']}'" : 'NULL') . " where `id_lets`='".makeSafe($selected_id)."'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo '<a href="lieu_et_scene_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: lieu_et_scene_after_update
	if(function_exists('lieu_et_scene_after_update')){
		$res = sql("SELECT * FROM `lieu_et_scene` WHERE `id_lets`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['id_lets'];
		$args = array();
		if(!lieu_et_scene_after_update($data, getMemberInfo(), $args)){ return; }
	}

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."' where tableName='lieu_et_scene' and pkValue='".makeSafe($selected_id)."'", $eo);

}

function lieu_et_scene_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0, $TemplateDV = '', $TemplateDVP = ''){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('lieu_et_scene');
	if(!$arrPerm[1] && $selected_id==''){ return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != ''){
		$dvprint = true;
	}

	$filterer_objet_present = thisOr(undo_magic_quotes($_REQUEST['filterer_objet_present']), '');
	$filterer_persos_present = thisOr(undo_magic_quotes($_REQUEST['filterer_persos_present']), '');
	$filterer_rattache_a_dos2j = thisOr(undo_magic_quotes($_REQUEST['filterer_rattache_a_dos2j']), '');
	$filterer_rattache_a_seq = thisOr(undo_magic_quotes($_REQUEST['filterer_rattache_a_seq']), '');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: difficulte_nivo
	$combo_difficulte_nivo = new Combo;
	$combo_difficulte_nivo->ListType = 0;
	$combo_difficulte_nivo->MultipleSeparator = ', ';
	$combo_difficulte_nivo->ListBoxHeight = 10;
	$combo_difficulte_nivo->RadiosPerLine = 1;
	if(is_file(dirname(__FILE__).'/hooks/lieu_et_scene.difficulte_nivo.csv')){
		$difficulte_nivo_data = addslashes(implode('', @file(dirname(__FILE__).'/hooks/lieu_et_scene.difficulte_nivo.csv')));
		$combo_difficulte_nivo->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions($difficulte_nivo_data)));
		$combo_difficulte_nivo->ListData = $combo_difficulte_nivo->ListItem;
	}else{
		$combo_difficulte_nivo->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions("intro;;facile;;moyen;;difficile")));
		$combo_difficulte_nivo->ListData = $combo_difficulte_nivo->ListItem;
	}
	$combo_difficulte_nivo->SelectName = 'difficulte_nivo';
	// combobox: objet_present
	$combo_objet_present = new DataCombo;
	// combobox: persos_present
	$combo_persos_present = new DataCombo;
	// combobox: rattache_a_dos2j
	$combo_rattache_a_dos2j = new DataCombo;
	// combobox: rattache_a_seq
	$combo_rattache_a_seq = new DataCombo;

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='lieu_et_scene' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='lieu_et_scene' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("select * from `lieu_et_scene` where `id_lets`='".makeSafe($selected_id)."'", $eo);
		if(!($row = db_fetch_array($res))){
			return error_message($Translation['No records found'], 'lieu_et_scene_view.php', false);
		}
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
		$combo_difficulte_nivo->SelectedData = $row['difficulte_nivo'];
		$combo_objet_present->SelectedData = $row['objet_present'];
		$combo_persos_present->SelectedData = $row['persos_present'];
		$combo_rattache_a_dos2j->SelectedData = $row['rattache_a_dos2j'];
		$combo_rattache_a_seq->SelectedData = $row['rattache_a_seq'];
	}else{
		$combo_difficulte_nivo->SelectedText = ( $_REQUEST['FilterField'][1]=='5' && $_REQUEST['FilterOperator'][1]=='<=>' ? (get_magic_quotes_gpc() ? stripslashes($_REQUEST['FilterValue'][1]) : $_REQUEST['FilterValue'][1]) : "");
		$combo_objet_present->SelectedData = $filterer_objet_present;
		$combo_persos_present->SelectedData = $filterer_persos_present;
		$combo_rattache_a_dos2j->SelectedData = $filterer_rattache_a_dos2j;
		$combo_rattache_a_seq->SelectedData = $filterer_rattache_a_seq;
	}
	$combo_difficulte_nivo->Render();
	$combo_objet_present->HTML = '<span id="objet_present-container' . $rnd1 . '"></span><input type="hidden" name="objet_present" id="objet_present' . $rnd1 . '" value="' . html_attr($combo_objet_present->SelectedData) . '">';
	$combo_objet_present->MatchText = '<span id="objet_present-container-readonly' . $rnd1 . '"></span><input type="hidden" name="objet_present" id="objet_present' . $rnd1 . '" value="' . html_attr($combo_objet_present->SelectedData) . '">';
	$combo_persos_present->HTML = '<span id="persos_present-container' . $rnd1 . '"></span><input type="hidden" name="persos_present" id="persos_present' . $rnd1 . '" value="' . html_attr($combo_persos_present->SelectedData) . '">';
	$combo_persos_present->MatchText = '<span id="persos_present-container-readonly' . $rnd1 . '"></span><input type="hidden" name="persos_present" id="persos_present' . $rnd1 . '" value="' . html_attr($combo_persos_present->SelectedData) . '">';
	$combo_rattache_a_dos2j->HTML = '<span id="rattache_a_dos2j-container' . $rnd1 . '"></span><input type="hidden" name="rattache_a_dos2j" id="rattache_a_dos2j' . $rnd1 . '" value="' . html_attr($combo_rattache_a_dos2j->SelectedData) . '">';
	$combo_rattache_a_dos2j->MatchText = '<span id="rattache_a_dos2j-container-readonly' . $rnd1 . '"></span><input type="hidden" name="rattache_a_dos2j" id="rattache_a_dos2j' . $rnd1 . '" value="' . html_attr($combo_rattache_a_dos2j->SelectedData) . '">';
	$combo_rattache_a_seq->HTML = '<span id="rattache_a_seq-container' . $rnd1 . '"></span><input type="hidden" name="rattache_a_seq" id="rattache_a_seq' . $rnd1 . '" value="' . html_attr($combo_rattache_a_seq->SelectedData) . '">';
	$combo_rattache_a_seq->MatchText = '<span id="rattache_a_seq-container-readonly' . $rnd1 . '"></span><input type="hidden" name="rattache_a_seq" id="rattache_a_seq' . $rnd1 . '" value="' . html_attr($combo_rattache_a_seq->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_objet_present__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['objet_present'] : $filterer_objet_present); ?>"};
		AppGini.current_persos_present__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['persos_present'] : $filterer_persos_present); ?>"};
		AppGini.current_rattache_a_dos2j__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['rattache_a_dos2j'] : $filterer_rattache_a_dos2j); ?>"};
		AppGini.current_rattache_a_seq__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['rattache_a_seq'] : $filterer_rattache_a_seq); ?>"};

		jQuery(function() {
			setTimeout(function(){
				if(typeof(objet_present_reload__RAND__) == 'function') objet_present_reload__RAND__();
				if(typeof(persos_present_reload__RAND__) == 'function') persos_present_reload__RAND__();
				if(typeof(rattache_a_dos2j_reload__RAND__) == 'function') rattache_a_dos2j_reload__RAND__();
				if(typeof(rattache_a_seq_reload__RAND__) == 'function') rattache_a_seq_reload__RAND__();
			}, 10); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function objet_present_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			$j("#objet_present-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_objet_present__RAND__.value, t: 'lieu_et_scene', f: 'objet_present' },
						success: function(resp){
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="objet_present"]').val(resp.results[0].id);
							$j('[id=objet_present-container-readonly__RAND__]').html('<span id="objet_present-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=Objets_view_parent]').hide(); }else{ $j('.btn[id=Objets_view_parent]').show(); }


							if(typeof(objet_present_update_autofills__RAND__) == 'function') objet_present_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term){ /* */ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ /* */ return { s: term, p: page, t: 'lieu_et_scene', f: 'objet_present' }; },
					results: function(resp, page){ /* */ return resp; }
				},
				escapeMarkup: function(str){ /* */ return str; }
			}).on('change', function(e){
				AppGini.current_objet_present__RAND__.value = e.added.id;
				AppGini.current_objet_present__RAND__.text = e.added.text;
				$j('[name="objet_present"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=Objets_view_parent]').hide(); }else{ $j('.btn[id=Objets_view_parent]').show(); }


				if(typeof(objet_present_update_autofills__RAND__) == 'function') objet_present_update_autofills__RAND__();
			});

			if(!$j("#objet_present-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_objet_present__RAND__.value, t: 'lieu_et_scene', f: 'objet_present' },
					success: function(resp){
						$j('[name="objet_present"]').val(resp.results[0].id);
						$j('[id=objet_present-container-readonly__RAND__]').html('<span id="objet_present-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=Objets_view_parent]').hide(); }else{ $j('.btn[id=Objets_view_parent]').show(); }

						if(typeof(objet_present_update_autofills__RAND__) == 'function') objet_present_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_objet_present__RAND__.value, t: 'lieu_et_scene', f: 'objet_present' },
				success: function(resp){
					$j('[id=objet_present-container__RAND__], [id=objet_present-container-readonly__RAND__]').html('<span id="objet_present-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=Objets_view_parent]').hide(); }else{ $j('.btn[id=Objets_view_parent]').show(); }

					if(typeof(objet_present_update_autofills__RAND__) == 'function') objet_present_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function persos_present_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			$j("#persos_present-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_persos_present__RAND__.value, t: 'lieu_et_scene', f: 'persos_present' },
						success: function(resp){
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="persos_present"]').val(resp.results[0].id);
							$j('[id=persos_present-container-readonly__RAND__]').html('<span id="persos_present-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=personnages_view_parent]').hide(); }else{ $j('.btn[id=personnages_view_parent]').show(); }


							if(typeof(persos_present_update_autofills__RAND__) == 'function') persos_present_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term){ /* */ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ /* */ return { s: term, p: page, t: 'lieu_et_scene', f: 'persos_present' }; },
					results: function(resp, page){ /* */ return resp; }
				},
				escapeMarkup: function(str){ /* */ return str; }
			}).on('change', function(e){
				AppGini.current_persos_present__RAND__.value = e.added.id;
				AppGini.current_persos_present__RAND__.text = e.added.text;
				$j('[name="persos_present"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=personnages_view_parent]').hide(); }else{ $j('.btn[id=personnages_view_parent]').show(); }


				if(typeof(persos_present_update_autofills__RAND__) == 'function') persos_present_update_autofills__RAND__();
			});

			if(!$j("#persos_present-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_persos_present__RAND__.value, t: 'lieu_et_scene', f: 'persos_present' },
					success: function(resp){
						$j('[name="persos_present"]').val(resp.results[0].id);
						$j('[id=persos_present-container-readonly__RAND__]').html('<span id="persos_present-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=personnages_view_parent]').hide(); }else{ $j('.btn[id=personnages_view_parent]').show(); }

						if(typeof(persos_present_update_autofills__RAND__) == 'function') persos_present_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_persos_present__RAND__.value, t: 'lieu_et_scene', f: 'persos_present' },
				success: function(resp){
					$j('[id=persos_present-container__RAND__], [id=persos_present-container-readonly__RAND__]').html('<span id="persos_present-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=personnages_view_parent]').hide(); }else{ $j('.btn[id=personnages_view_parent]').show(); }

					if(typeof(persos_present_update_autofills__RAND__) == 'function') persos_present_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function rattache_a_dos2j_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			$j("#rattache_a_dos2j-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_rattache_a_dos2j__RAND__.value, t: 'lieu_et_scene', f: 'rattache_a_dos2j' },
						success: function(resp){
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="rattache_a_dos2j"]').val(resp.results[0].id);
							$j('[id=rattache_a_dos2j-container-readonly__RAND__]').html('<span id="rattache_a_dos2j-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=Dossier_histoire_view_parent]').hide(); }else{ $j('.btn[id=Dossier_histoire_view_parent]').show(); }


							if(typeof(rattache_a_dos2j_update_autofills__RAND__) == 'function') rattache_a_dos2j_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term){ /* */ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ /* */ return { s: term, p: page, t: 'lieu_et_scene', f: 'rattache_a_dos2j' }; },
					results: function(resp, page){ /* */ return resp; }
				},
				escapeMarkup: function(str){ /* */ return str; }
			}).on('change', function(e){
				AppGini.current_rattache_a_dos2j__RAND__.value = e.added.id;
				AppGini.current_rattache_a_dos2j__RAND__.text = e.added.text;
				$j('[name="rattache_a_dos2j"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=Dossier_histoire_view_parent]').hide(); }else{ $j('.btn[id=Dossier_histoire_view_parent]').show(); }


				if(typeof(rattache_a_dos2j_update_autofills__RAND__) == 'function') rattache_a_dos2j_update_autofills__RAND__();
			});

			if(!$j("#rattache_a_dos2j-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_rattache_a_dos2j__RAND__.value, t: 'lieu_et_scene', f: 'rattache_a_dos2j' },
					success: function(resp){
						$j('[name="rattache_a_dos2j"]').val(resp.results[0].id);
						$j('[id=rattache_a_dos2j-container-readonly__RAND__]').html('<span id="rattache_a_dos2j-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=Dossier_histoire_view_parent]').hide(); }else{ $j('.btn[id=Dossier_histoire_view_parent]').show(); }

						if(typeof(rattache_a_dos2j_update_autofills__RAND__) == 'function') rattache_a_dos2j_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_rattache_a_dos2j__RAND__.value, t: 'lieu_et_scene', f: 'rattache_a_dos2j' },
				success: function(resp){
					$j('[id=rattache_a_dos2j-container__RAND__], [id=rattache_a_dos2j-container-readonly__RAND__]').html('<span id="rattache_a_dos2j-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=Dossier_histoire_view_parent]').hide(); }else{ $j('.btn[id=Dossier_histoire_view_parent]').show(); }

					if(typeof(rattache_a_dos2j_update_autofills__RAND__) == 'function') rattache_a_dos2j_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function rattache_a_seq_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			$j("#rattache_a_seq-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_rattache_a_seq__RAND__.value, t: 'lieu_et_scene', f: 'rattache_a_seq' },
						success: function(resp){
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="rattache_a_seq"]').val(resp.results[0].id);
							$j('[id=rattache_a_seq-container-readonly__RAND__]').html('<span id="rattache_a_seq-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=sequence_view_parent]').hide(); }else{ $j('.btn[id=sequence_view_parent]').show(); }


							if(typeof(rattache_a_seq_update_autofills__RAND__) == 'function') rattache_a_seq_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term){ /* */ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ /* */ return { s: term, p: page, t: 'lieu_et_scene', f: 'rattache_a_seq' }; },
					results: function(resp, page){ /* */ return resp; }
				},
				escapeMarkup: function(str){ /* */ return str; }
			}).on('change', function(e){
				AppGini.current_rattache_a_seq__RAND__.value = e.added.id;
				AppGini.current_rattache_a_seq__RAND__.text = e.added.text;
				$j('[name="rattache_a_seq"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=sequence_view_parent]').hide(); }else{ $j('.btn[id=sequence_view_parent]').show(); }


				if(typeof(rattache_a_seq_update_autofills__RAND__) == 'function') rattache_a_seq_update_autofills__RAND__();
			});

			if(!$j("#rattache_a_seq-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_rattache_a_seq__RAND__.value, t: 'lieu_et_scene', f: 'rattache_a_seq' },
					success: function(resp){
						$j('[name="rattache_a_seq"]').val(resp.results[0].id);
						$j('[id=rattache_a_seq-container-readonly__RAND__]').html('<span id="rattache_a_seq-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=sequence_view_parent]').hide(); }else{ $j('.btn[id=sequence_view_parent]').show(); }

						if(typeof(rattache_a_seq_update_autofills__RAND__) == 'function') rattache_a_seq_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_rattache_a_seq__RAND__.value, t: 'lieu_et_scene', f: 'rattache_a_seq' },
				success: function(resp){
					$j('[id=rattache_a_seq-container__RAND__], [id=rattache_a_seq-container-readonly__RAND__]').html('<span id="rattache_a_seq-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=sequence_view_parent]').hide(); }else{ $j('.btn[id=sequence_view_parent]').show(); }

					if(typeof(rattache_a_seq_update_autofills__RAND__) == 'function') rattache_a_seq_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	if($dvprint){
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/lieu_et_scene_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	}else{
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/lieu_et_scene_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Lieu et scene details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert){
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return lieu_et_scene_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return lieu_et_scene_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']){
		$backAction = 'AppGini.closeParentModal(); return false;';
	}else{
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id){
		if(!$_REQUEST['Embedded']) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate){
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return lieu_et_scene_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)){
		$jsReadOnly .= "\tjQuery('#nom_du_lieu').replaceWith('<div class=\"form-control-static\" id=\"nom_du_lieu\">' + (jQuery('#nom_du_lieu').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#illustration').replaceWith('<div class=\"form-control-static\" id=\"illustration\">' + (jQuery('#illustration').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#difficulte_nivo').replaceWith('<div class=\"form-control-static\" id=\"difficulte_nivo\">' + (jQuery('#difficulte_nivo').val() || '') + '</div>'); jQuery('#difficulte_nivo-multi-selection-help').hide();\n";
		$jsReadOnly .= "\tjQuery('#objet_present').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#objet_present_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#persos_present').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#persos_present_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#rattache_a_dos2j').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#rattache_a_dos2j_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#rattache_a_seq').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#rattache_a_seq_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	}elseif($AllowInsert){
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(difficulte_nivo)%%>', $combo_difficulte_nivo->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(difficulte_nivo)%%>', $combo_difficulte_nivo->SelectedData, $templateCode);
	$templateCode = str_replace('<%%COMBO(objet_present)%%>', $combo_objet_present->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(objet_present)%%>', $combo_objet_present->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(objet_present)%%>', urlencode($combo_objet_present->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(persos_present)%%>', $combo_persos_present->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(persos_present)%%>', $combo_persos_present->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(persos_present)%%>', urlencode($combo_persos_present->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(rattache_a_dos2j)%%>', $combo_rattache_a_dos2j->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(rattache_a_dos2j)%%>', $combo_rattache_a_dos2j->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(rattache_a_dos2j)%%>', urlencode($combo_rattache_a_dos2j->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(rattache_a_seq)%%>', $combo_rattache_a_seq->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(rattache_a_seq)%%>', $combo_rattache_a_seq->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(rattache_a_seq)%%>', urlencode($combo_rattache_a_seq->MatchText), $templateCode);

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array(  'objet_present' => array('Objets', 'Objet present'), 'persos_present' => array('personnages', 'Persos present'), 'rattache_a_dos2j' => array('Dossier_histoire', 'Rattache a dos2j'), 'rattache_a_seq' => array('sequence', 'Rattache a seq'));
	foreach($lookup_fields as $luf => $ptfc){
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']){
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] && !$_REQUEST['Embedded']){
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id_lets)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(nom_du_lieu)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(illustration)%%>', ($noUploads ? '' : '<input type=hidden name=MAX_FILE_SIZE value=102400>'.$Translation['upload image'].' <input type="file" name="illustration" id="illustration">'), $templateCode);
	if($AllowUpdate && $row['illustration'] != ''){
		$templateCode = str_replace('<%%REMOVEFILE(illustration)%%>', '<br><input type="checkbox" name="illustration_remove" id="illustration_remove" value="1"> <label for="illustration_remove" style="color: red; font-weight: bold;">'.$Translation['remove image'].'</label>', $templateCode);
	}else{
		$templateCode = str_replace('<%%REMOVEFILE(illustration)%%>', '', $templateCode);
	}
	$templateCode = str_replace('<%%UPLOADFILE(description)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(difficulte_nivo)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(condition_entree)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(condition_sortie)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(objet_present)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(persos_present)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(creer_par)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(rattache_a_dos2j)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(rattache_a_seq)%%>', '', $templateCode);

	// process values
	if($selected_id){
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id_lets)%%>', safe_html($urow['id_lets']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id_lets)%%>', html_attr($row['id_lets']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id_lets)%%>', urlencode($urow['id_lets']), $templateCode);
		if($dvprint || (!$AllowUpdate && !$AllowInsert)){
			$templateCode = str_replace('<%%VALUE(nom_du_lieu)%%>', safe_html($urow['nom_du_lieu']), $templateCode);
		}else{
			$templateCode = str_replace('<%%VALUE(nom_du_lieu)%%>', html_attr($row['nom_du_lieu']), $templateCode);
		}
		$templateCode = str_replace('<%%URLVALUE(nom_du_lieu)%%>', urlencode($urow['nom_du_lieu']), $templateCode);
		$row['illustration'] = ($row['illustration'] != '' ? $row['illustration'] : 'blank.gif');
		if( $dvprint) $templateCode = str_replace('<%%VALUE(illustration)%%>', safe_html($urow['illustration']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(illustration)%%>', html_attr($row['illustration']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(illustration)%%>', urlencode($urow['illustration']), $templateCode);
		if($AllowUpdate || $AllowInsert){
			$templateCode = str_replace('<%%HTMLAREA(description)%%>', '<textarea name="description" id="description" rows="5">' . html_attr($row['description']) . '</textarea>', $templateCode);
		}else{
			$templateCode = str_replace('<%%HTMLAREA(description)%%>', '<div id="description" class="form-control-static">' . $row['description'] . '</div>', $templateCode);
		}
		$templateCode = str_replace('<%%VALUE(description)%%>', nl2br($row['description']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(description)%%>', urlencode($urow['description']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(difficulte_nivo)%%>', safe_html($urow['difficulte_nivo']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(difficulte_nivo)%%>', html_attr($row['difficulte_nivo']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(difficulte_nivo)%%>', urlencode($urow['difficulte_nivo']), $templateCode);
		if($AllowUpdate || $AllowInsert){
			$templateCode = str_replace('<%%HTMLAREA(condition_entree)%%>', '<textarea name="condition_entree" id="condition_entree" rows="5">' . html_attr($row['condition_entree']) . '</textarea>', $templateCode);
		}else{
			$templateCode = str_replace('<%%HTMLAREA(condition_entree)%%>', '<div id="condition_entree" class="form-control-static">' . $row['condition_entree'] . '</div>', $templateCode);
		}
		$templateCode = str_replace('<%%VALUE(condition_entree)%%>', nl2br($row['condition_entree']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(condition_entree)%%>', urlencode($urow['condition_entree']), $templateCode);
		if($AllowUpdate || $AllowInsert){
			$templateCode = str_replace('<%%HTMLAREA(condition_sortie)%%>', '<textarea name="condition_sortie" id="condition_sortie" rows="5">' . html_attr($row['condition_sortie']) . '</textarea>', $templateCode);
		}else{
			$templateCode = str_replace('<%%HTMLAREA(condition_sortie)%%>', '<div id="condition_sortie" class="form-control-static">' . $row['condition_sortie'] . '</div>', $templateCode);
		}
		$templateCode = str_replace('<%%VALUE(condition_sortie)%%>', nl2br($row['condition_sortie']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(condition_sortie)%%>', urlencode($urow['condition_sortie']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(objet_present)%%>', safe_html($urow['objet_present']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(objet_present)%%>', html_attr($row['objet_present']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(objet_present)%%>', urlencode($urow['objet_present']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(persos_present)%%>', safe_html($urow['persos_present']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(persos_present)%%>', html_attr($row['persos_present']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(persos_present)%%>', urlencode($urow['persos_present']), $templateCode);
		$templateCode = str_replace('<%%VALUE(creer_par)%%>', safe_html($urow['creer_par']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(creer_par)%%>', urlencode($urow['creer_par']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(rattache_a_dos2j)%%>', safe_html($urow['rattache_a_dos2j']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(rattache_a_dos2j)%%>', html_attr($row['rattache_a_dos2j']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(rattache_a_dos2j)%%>', urlencode($urow['rattache_a_dos2j']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(rattache_a_seq)%%>', safe_html($urow['rattache_a_seq']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(rattache_a_seq)%%>', html_attr($row['rattache_a_seq']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(rattache_a_seq)%%>', urlencode($urow['rattache_a_seq']), $templateCode);
	}else{
		$templateCode = str_replace('<%%VALUE(id_lets)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id_lets)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(nom_du_lieu)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(nom_du_lieu)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(illustration)%%>', 'blank.gif', $templateCode);
		$templateCode = str_replace('<%%HTMLAREA(description)%%>', '<textarea name="description" id="description" rows="5"></textarea>', $templateCode);
		$templateCode = str_replace('<%%VALUE(difficulte_nivo)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(difficulte_nivo)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%HTMLAREA(condition_entree)%%>', '<textarea name="condition_entree" id="condition_entree" rows="5">Pour acc&#233;der &#224; cette sc&#232;ne...</textarea>', $templateCode);
		$templateCode = str_replace('<%%HTMLAREA(condition_sortie)%%>', '<textarea name="condition_sortie" id="condition_sortie" rows="5">Pour sortir de cette sc&#232;ne...</textarea>', $templateCode);
		$templateCode = str_replace('<%%VALUE(objet_present)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(objet_present)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(persos_present)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(persos_present)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(creer_par)%%>', '<%%creatorUsername%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(creer_par)%%>', urlencode('<%%creatorUsername%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(rattache_a_dos2j)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(rattache_a_dos2j)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(rattache_a_seq)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(rattache_a_seq)%%>', urlencode(''), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode = str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == ''){
		$templateCode .= "\n\n<script>\$j(function(){\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption){
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id){
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('lieu_et_scene');
	if($selected_id){
		$jdata = get_joined_record('lieu_et_scene', $selected_id);
		if($jdata === false) $jdata = get_defaults('lieu_et_scene');
		$rdata = $row;
	}
	$templateCode .= loadView('lieu_et_scene-ajax-cache', array('rdata' => $rdata, 'jdata' => $jdata));

	// hook: lieu_et_scene_dv
	if(function_exists('lieu_et_scene_dv')){
		$args=array();
		lieu_et_scene_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>