<?php
// This script and data application were generated by AppGini 5.75
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/lieu_et_scene.php");
	include("$currDir/lieu_et_scene_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('lieu_et_scene');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "lieu_et_scene";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(   
		"`lieu_et_scene`.`id_lets`" => "id_lets",
		"`lieu_et_scene`.`nom_du_lieu`" => "nom_du_lieu",
		"`lieu_et_scene`.`illustration`" => "illustration",
		"`lieu_et_scene`.`description`" => "description",
		"`lieu_et_scene`.`difficulte_nivo`" => "difficulte_nivo",
		"`lieu_et_scene`.`condition_entree`" => "condition_entree",
		"`lieu_et_scene`.`condition_sortie`" => "condition_sortie",
		"IF(    CHAR_LENGTH(`Objets1`.`nom_objet`) || CHAR_LENGTH(`Objets1`.`illustration`), CONCAT_WS('',   `Objets1`.`nom_objet`, `Objets1`.`illustration`), '') /* Objet present */" => "objet_present",
		"IF(    CHAR_LENGTH(`personnages1`.`nom`) || CHAR_LENGTH(`personnages1`.`illustration`), CONCAT_WS('',   `personnages1`.`nom`, `personnages1`.`illustration`), '') /* Persos present */" => "persos_present",
		"`lieu_et_scene`.`creer_par`" => "creer_par",
		"IF(    CHAR_LENGTH(`Dossier_histoire1`.`titre_histoire`), CONCAT_WS('',   `Dossier_histoire1`.`titre_histoire`), '') /* Rattache a dos2j */" => "rattache_a_dos2j",
		"IF(    CHAR_LENGTH(`sequence1`.`numero_ordre`) || CHAR_LENGTH(`sequence1`.`titre`), CONCAT_WS('',   `sequence1`.`numero_ordre`, ' ', `sequence1`.`titre`), '') /* Rattache a seq */" => "rattache_a_seq"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`lieu_et_scene`.`id_lets`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
		7 => 7,
		8 => 8,
		9 => 9,
		10 => 10,
		11 => '`Dossier_histoire1`.`titre_histoire`',
		12 => 12
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(   
		"`lieu_et_scene`.`id_lets`" => "id_lets",
		"`lieu_et_scene`.`nom_du_lieu`" => "nom_du_lieu",
		"`lieu_et_scene`.`illustration`" => "illustration",
		"`lieu_et_scene`.`description`" => "description",
		"`lieu_et_scene`.`difficulte_nivo`" => "difficulte_nivo",
		"`lieu_et_scene`.`condition_entree`" => "condition_entree",
		"`lieu_et_scene`.`condition_sortie`" => "condition_sortie",
		"IF(    CHAR_LENGTH(`Objets1`.`nom_objet`) || CHAR_LENGTH(`Objets1`.`illustration`), CONCAT_WS('',   `Objets1`.`nom_objet`, `Objets1`.`illustration`), '') /* Objet present */" => "objet_present",
		"IF(    CHAR_LENGTH(`personnages1`.`nom`) || CHAR_LENGTH(`personnages1`.`illustration`), CONCAT_WS('',   `personnages1`.`nom`, `personnages1`.`illustration`), '') /* Persos present */" => "persos_present",
		"`lieu_et_scene`.`creer_par`" => "creer_par",
		"IF(    CHAR_LENGTH(`Dossier_histoire1`.`titre_histoire`), CONCAT_WS('',   `Dossier_histoire1`.`titre_histoire`), '') /* Rattache a dos2j */" => "rattache_a_dos2j",
		"IF(    CHAR_LENGTH(`sequence1`.`numero_ordre`) || CHAR_LENGTH(`sequence1`.`titre`), CONCAT_WS('',   `sequence1`.`numero_ordre`, ' ', `sequence1`.`titre`), '') /* Rattache a seq */" => "rattache_a_seq"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(   
		"`lieu_et_scene`.`id_lets`" => "Id lets",
		"`lieu_et_scene`.`nom_du_lieu`" => "Nom du lieu",
		"`lieu_et_scene`.`description`" => "Description",
		"`lieu_et_scene`.`difficulte_nivo`" => "Difficulte nivo",
		"`lieu_et_scene`.`condition_entree`" => "Condition entree",
		"`lieu_et_scene`.`condition_sortie`" => "Condition sortie",
		"IF(    CHAR_LENGTH(`Objets1`.`nom_objet`) || CHAR_LENGTH(`Objets1`.`illustration`), CONCAT_WS('',   `Objets1`.`nom_objet`, `Objets1`.`illustration`), '') /* Objet present */" => "Objet present",
		"IF(    CHAR_LENGTH(`personnages1`.`nom`) || CHAR_LENGTH(`personnages1`.`illustration`), CONCAT_WS('',   `personnages1`.`nom`, `personnages1`.`illustration`), '') /* Persos present */" => "Persos present",
		"`lieu_et_scene`.`creer_par`" => "Creer par",
		"IF(    CHAR_LENGTH(`Dossier_histoire1`.`titre_histoire`), CONCAT_WS('',   `Dossier_histoire1`.`titre_histoire`), '') /* Rattache a dos2j */" => "Rattache a dos2j",
		"IF(    CHAR_LENGTH(`sequence1`.`numero_ordre`) || CHAR_LENGTH(`sequence1`.`titre`), CONCAT_WS('',   `sequence1`.`numero_ordre`, ' ', `sequence1`.`titre`), '') /* Rattache a seq */" => "Rattache a seq"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(   
		"`lieu_et_scene`.`id_lets`" => "id_lets",
		"`lieu_et_scene`.`nom_du_lieu`" => "nom_du_lieu",
		"`lieu_et_scene`.`description`" => "description",
		"`lieu_et_scene`.`difficulte_nivo`" => "difficulte_nivo",
		"`lieu_et_scene`.`condition_entree`" => "condition_entree",
		"`lieu_et_scene`.`condition_sortie`" => "condition_sortie",
		"IF(    CHAR_LENGTH(`Objets1`.`nom_objet`) || CHAR_LENGTH(`Objets1`.`illustration`), CONCAT_WS('',   `Objets1`.`nom_objet`, `Objets1`.`illustration`), '') /* Objet present */" => "objet_present",
		"IF(    CHAR_LENGTH(`personnages1`.`nom`) || CHAR_LENGTH(`personnages1`.`illustration`), CONCAT_WS('',   `personnages1`.`nom`, `personnages1`.`illustration`), '') /* Persos present */" => "persos_present",
		"`lieu_et_scene`.`creer_par`" => "creer_par",
		"IF(    CHAR_LENGTH(`Dossier_histoire1`.`titre_histoire`), CONCAT_WS('',   `Dossier_histoire1`.`titre_histoire`), '') /* Rattache a dos2j */" => "rattache_a_dos2j",
		"IF(    CHAR_LENGTH(`sequence1`.`numero_ordre`) || CHAR_LENGTH(`sequence1`.`titre`), CONCAT_WS('',   `sequence1`.`numero_ordre`, ' ', `sequence1`.`titre`), '') /* Rattache a seq */" => "rattache_a_seq"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array(  'objet_present' => 'Objet present', 'persos_present' => 'Persos present', 'rattache_a_dos2j' => 'Rattache a dos2j', 'rattache_a_seq' => 'Rattache a seq');

	$x->QueryFrom = "`lieu_et_scene` LEFT JOIN `Objets` as Objets1 ON `Objets1`.`id_objet`=`lieu_et_scene`.`objet_present` LEFT JOIN `personnages` as personnages1 ON `personnages1`.`id_perso`=`lieu_et_scene`.`persos_present` LEFT JOIN `Dossier_histoire` as Dossier_histoire1 ON `Dossier_histoire1`.`id2dossier`=`lieu_et_scene`.`rattache_a_dos2j` LEFT JOIN `sequence` as sequence1 ON `sequence1`.`id_sequence`=`lieu_et_scene`.`rattache_a_seq` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "lieu_et_scene_view.php";
	$x->RedirectAfterInsert = "lieu_et_scene_view.php?SelectedID=#ID#";
	$x->TableTitle = "Lieu et scene";
	$x->TableIcon = "resources/table_icons/application_view_gallery.png";
	$x->PrimaryKey = "`lieu_et_scene`.`id_lets`";

	$x->ColWidth   = array(  150, 150, 150, 150);
	$x->ColCaption = array("Nom du lieu", "Illustration", "Description", "Difficulte nivo");
	$x->ColFieldName = array('nom_du_lieu', 'illustration', 'description', 'difficulte_nivo');
	$x->ColNumber  = array(2, 3, 4, 5);

	// template paths below are based on the app main directory
	$x->Template = 'templates/lieu_et_scene_templateTV.html';
	$x->SelectedTemplate = 'templates/lieu_et_scene_templateTVS.html';
	$x->TemplateDV = 'templates/lieu_et_scene_templateDV.html';
	$x->TemplateDVP = 'templates/lieu_et_scene_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `lieu_et_scene`.`id_lets`=membership_userrecords.pkValue and membership_userrecords.tableName='lieu_et_scene' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `lieu_et_scene`.`id_lets`=membership_userrecords.pkValue and membership_userrecords.tableName='lieu_et_scene' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`lieu_et_scene`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: lieu_et_scene_init
	$render=TRUE;
	if(function_exists('lieu_et_scene_init')){
		$args=array();
		$render=lieu_et_scene_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: lieu_et_scene_header
	$headerCode='';
	if(function_exists('lieu_et_scene_header')){
		$args=array();
		$headerCode=lieu_et_scene_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: lieu_et_scene_footer
	$footerCode='';
	if(function_exists('lieu_et_scene_footer')){
		$args=array();
		$footerCode=lieu_et_scene_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>