<?php

// Data functions (insert, update, delete, form) for table Objets

// This script and data application were generated by AppGini 5.75
// Download AppGini for free from https://bigprof.com/appgini/download/

function Objets_insert(){
	global $Translation;

	// mm: can member insert record?
	$arrPerm=getTablePermissions('Objets');
	if(!$arrPerm[1]){
		return false;
	}

	$data['nom_objet'] = makeSafe($_REQUEST['nom_objet']);
		if($data['nom_objet'] == empty_lookup_value){ $data['nom_objet'] = ''; }
	$data['typologie'] = makeSafe($_REQUEST['typologie']);
		if($data['typologie'] == empty_lookup_value){ $data['typologie'] = ''; }
	$data['Aquoisertil'] = makeSafe($_REQUEST['Aquoisertil']);
		if($data['Aquoisertil'] == empty_lookup_value){ $data['Aquoisertil'] = ''; }
	$data['Contient'] = makeSafe($_REQUEST['Contient']);
		if($data['Contient'] == empty_lookup_value){ $data['Contient'] = ''; }
	$data['creer_par'] = parseCode('<%%creatorUsername%%>', true);
	$data['rattache_a_dos2j'] = makeSafe($_REQUEST['rattache_a_dos2j']);
		if($data['rattache_a_dos2j'] == empty_lookup_value){ $data['rattache_a_dos2j'] = ''; }
	$data['rattache_a_seq'] = makeSafe($_REQUEST['rattache_a_seq']);
		if($data['rattache_a_seq'] == empty_lookup_value){ $data['rattache_a_seq'] = ''; }
	$data['illustration'] = PrepareUploadedFile('illustration', 102400,'jpg|jpeg|gif|png', false, '');
	if($data['illustration']) createThumbnail($data['illustration'], getThumbnailSpecs('Objets', 'illustration', 'tv'));
	if($data['illustration']) createThumbnail($data['illustration'], getThumbnailSpecs('Objets', 'illustration', 'dv'));
	if($data['nom_objet']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Nom objet': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}

	/* for empty upload fields, when saving a copy of an existing record, copy the original upload field */
	if($_REQUEST['SelectedID']){
		$res = sql("select * from Objets where id_objet='" . makeSafe($_REQUEST['SelectedID']) . "'", $eo);
		if($row = db_fetch_assoc($res)){
			if(!$data['illustration']) $data['illustration'] = makeSafe($row['illustration']);
		}
	}

	// hook: Objets_before_insert
	if(function_exists('Objets_before_insert')){
		$args=array();
		if(!Objets_before_insert($data, getMemberInfo(), $args)){ return false; }
	}

	$o = array('silentErrors' => true);
	sql('insert into `Objets` set       `nom_objet`=' . (($data['nom_objet'] !== '' && $data['nom_objet'] !== NULL) ? "'{$data['nom_objet']}'" : 'NULL') . ', ' . ($data['illustration'] != '' ? "`illustration`='{$data['illustration']}'" : '`illustration`=NULL') . ', `typologie`=' . (($data['typologie'] !== '' && $data['typologie'] !== NULL) ? "'{$data['typologie']}'" : 'NULL') . ', `Aquoisertil`=' . (($data['Aquoisertil'] !== '' && $data['Aquoisertil'] !== NULL) ? "'{$data['Aquoisertil']}'" : 'NULL') . ', `Contient`=' . (($data['Contient'] !== '' && $data['Contient'] !== NULL) ? "'{$data['Contient']}'" : 'NULL') . ', `creer_par`=' . "'{$data['creer_par']}'" . ', `rattache_a_dos2j`=' . (($data['rattache_a_dos2j'] !== '' && $data['rattache_a_dos2j'] !== NULL) ? "'{$data['rattache_a_dos2j']}'" : 'NULL') . ', `rattache_a_seq`=' . (($data['rattache_a_seq'] !== '' && $data['rattache_a_seq'] !== NULL) ? "'{$data['rattache_a_seq']}'" : 'NULL'), $o);
	if($o['error']!=''){
		echo $o['error'];
		echo "<a href=\"Objets_view.php?addNew_x=1\">{$Translation['< back']}</a>";
		exit;
	}

	$recID = db_insert_id(db_link());

	// hook: Objets_after_insert
	if(function_exists('Objets_after_insert')){
		$res = sql("select * from `Objets` where `id_objet`='" . makeSafe($recID, false) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=array();
		if(!Objets_after_insert($data, getMemberInfo(), $args)){ return $recID; }
	}

	// mm: save ownership data
	set_record_owner('Objets', $recID, getLoggedMemberID());

	return $recID;
}

function Objets_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false){
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('Objets');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='Objets' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='Objets' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: Objets_before_delete
	if(function_exists('Objets_before_delete')){
		$args=array();
		if(!Objets_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	// child table: Objets
	$res = sql("select `id_objet` from `Objets` where `id_objet`='$selected_id'", $eo);
	$id_objet = db_fetch_row($res);
	$rires = sql("select count(1) from `Objets` where `Contient`='".addslashes($id_objet[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "Objets", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "Objets", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='Objets_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='Objets_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	// child table: personnages
	$res = sql("select `id_objet` from `Objets` where `id_objet`='$selected_id'", $eo);
	$id_objet = db_fetch_row($res);
	$rires = sql("select count(1) from `personnages` where `quepossedetil`='".addslashes($id_objet[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "personnages", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "personnages", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='Objets_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='Objets_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	// child table: lieu_et_scene
	$res = sql("select `id_objet` from `Objets` where `id_objet`='$selected_id'", $eo);
	$id_objet = db_fetch_row($res);
	$rires = sql("select count(1) from `lieu_et_scene` where `objet_present`='".addslashes($id_objet[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "lieu_et_scene", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "lieu_et_scene", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='Objets_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='Objets_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	sql("delete from `Objets` where `id_objet`='$selected_id'", $eo);

	// hook: Objets_after_delete
	if(function_exists('Objets_after_delete')){
		$args=array();
		Objets_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='Objets' and pkValue='$selected_id'", $eo);
}

function Objets_update($selected_id){
	global $Translation;

	// mm: can member edit record?
	$arrPerm=getTablePermissions('Objets');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='Objets' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='Objets' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['nom_objet'] = makeSafe($_REQUEST['nom_objet']);
		if($data['nom_objet'] == empty_lookup_value){ $data['nom_objet'] = ''; }
	if($data['nom_objet']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Nom objet': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['typologie'] = makeSafe($_REQUEST['typologie']);
		if($data['typologie'] == empty_lookup_value){ $data['typologie'] = ''; }
	$data['Aquoisertil'] = makeSafe($_REQUEST['Aquoisertil']);
		if($data['Aquoisertil'] == empty_lookup_value){ $data['Aquoisertil'] = ''; }
	$data['Contient'] = makeSafe($_REQUEST['Contient']);
		if($data['Contient'] == empty_lookup_value){ $data['Contient'] = ''; }
	$data['rattache_a_dos2j'] = makeSafe($_REQUEST['rattache_a_dos2j']);
		if($data['rattache_a_dos2j'] == empty_lookup_value){ $data['rattache_a_dos2j'] = ''; }
	$data['rattache_a_seq'] = makeSafe($_REQUEST['rattache_a_seq']);
		if($data['rattache_a_seq'] == empty_lookup_value){ $data['rattache_a_seq'] = ''; }
	$data['selectedID']=makeSafe($selected_id);
	if($_REQUEST['illustration_remove'] == 1){
		$data['illustration'] = '';
	}else{
		$data['illustration'] = PrepareUploadedFile('illustration', 102400, 'jpg|jpeg|gif|png', false, "");
		if($data['illustration']) createThumbnail($data['illustration'], getThumbnailSpecs('Objets', 'illustration', 'tv'));
		if($data['illustration']) createThumbnail($data['illustration'], getThumbnailSpecs('Objets', 'illustration', 'dv'));
	}

	// hook: Objets_before_update
	if(function_exists('Objets_before_update')){
		$args=array();
		if(!Objets_before_update($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('update `Objets` set       `nom_objet`=' . (($data['nom_objet'] !== '' && $data['nom_objet'] !== NULL) ? "'{$data['nom_objet']}'" : 'NULL') . ', ' . ($data['illustration']!='' ? "`illustration`='{$data['illustration']}'" : ($_REQUEST['illustration_remove'] != 1 ? '`illustration`=`illustration`' : '`illustration`=NULL')) . ', `typologie`=' . (($data['typologie'] !== '' && $data['typologie'] !== NULL) ? "'{$data['typologie']}'" : 'NULL') . ', `Aquoisertil`=' . (($data['Aquoisertil'] !== '' && $data['Aquoisertil'] !== NULL) ? "'{$data['Aquoisertil']}'" : 'NULL') . ', `Contient`=' . (($data['Contient'] !== '' && $data['Contient'] !== NULL) ? "'{$data['Contient']}'" : 'NULL') . ', `rattache_a_dos2j`=' . (($data['rattache_a_dos2j'] !== '' && $data['rattache_a_dos2j'] !== NULL) ? "'{$data['rattache_a_dos2j']}'" : 'NULL') . ', `rattache_a_seq`=' . (($data['rattache_a_seq'] !== '' && $data['rattache_a_seq'] !== NULL) ? "'{$data['rattache_a_seq']}'" : 'NULL') . " where `id_objet`='".makeSafe($selected_id)."'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo '<a href="Objets_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: Objets_after_update
	if(function_exists('Objets_after_update')){
		$res = sql("SELECT * FROM `Objets` WHERE `id_objet`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['id_objet'];
		$args = array();
		if(!Objets_after_update($data, getMemberInfo(), $args)){ return; }
	}

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."' where tableName='Objets' and pkValue='".makeSafe($selected_id)."'", $eo);

}

function Objets_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0, $TemplateDV = '', $TemplateDVP = ''){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('Objets');
	if(!$arrPerm[1] && $selected_id==''){ return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != ''){
		$dvprint = true;
	}

	$filterer_Contient = thisOr(undo_magic_quotes($_REQUEST['filterer_Contient']), '');
	$filterer_rattache_a_dos2j = thisOr(undo_magic_quotes($_REQUEST['filterer_rattache_a_dos2j']), '');
	$filterer_rattache_a_seq = thisOr(undo_magic_quotes($_REQUEST['filterer_rattache_a_seq']), '');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: typologie
	$combo_typologie = new Combo;
	$combo_typologie->ListType = 0;
	$combo_typologie->MultipleSeparator = ', ';
	$combo_typologie->ListBoxHeight = 10;
	$combo_typologie->RadiosPerLine = 1;
	if(is_file(dirname(__FILE__).'/hooks/Objets.typologie.csv')){
		$typologie_data = addslashes(implode('', @file(dirname(__FILE__).'/hooks/Objets.typologie.csv')));
		$combo_typologie->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions($typologie_data)));
		$combo_typologie->ListData = $combo_typologie->ListItem;
	}else{
		$combo_typologie->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions("aide;;obstacle;;neutre")));
		$combo_typologie->ListData = $combo_typologie->ListItem;
	}
	$combo_typologie->SelectName = 'typologie';
	// combobox: Contient
	$combo_Contient = new DataCombo;
	// combobox: rattache_a_dos2j
	$combo_rattache_a_dos2j = new DataCombo;
	// combobox: rattache_a_seq
	$combo_rattache_a_seq = new DataCombo;

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='Objets' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='Objets' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("select * from `Objets` where `id_objet`='".makeSafe($selected_id)."'", $eo);
		if(!($row = db_fetch_array($res))){
			return error_message($Translation['No records found'], 'Objets_view.php', false);
		}
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
		$combo_typologie->SelectedData = $row['typologie'];
		$combo_Contient->SelectedData = $row['Contient'];
		$combo_rattache_a_dos2j->SelectedData = $row['rattache_a_dos2j'];
		$combo_rattache_a_seq->SelectedData = $row['rattache_a_seq'];
	}else{
		$combo_typologie->SelectedText = ( $_REQUEST['FilterField'][1]=='4' && $_REQUEST['FilterOperator'][1]=='<=>' ? (get_magic_quotes_gpc() ? stripslashes($_REQUEST['FilterValue'][1]) : $_REQUEST['FilterValue'][1]) : "");
		$combo_Contient->SelectedData = $filterer_Contient;
		$combo_rattache_a_dos2j->SelectedData = $filterer_rattache_a_dos2j;
		$combo_rattache_a_seq->SelectedData = $filterer_rattache_a_seq;
	}
	$combo_typologie->Render();
	$combo_Contient->HTML = '<span id="Contient-container' . $rnd1 . '"></span><input type="hidden" name="Contient" id="Contient' . $rnd1 . '" value="' . html_attr($combo_Contient->SelectedData) . '">';
	$combo_Contient->MatchText = '<span id="Contient-container-readonly' . $rnd1 . '"></span><input type="hidden" name="Contient" id="Contient' . $rnd1 . '" value="' . html_attr($combo_Contient->SelectedData) . '">';
	$combo_rattache_a_dos2j->HTML = '<span id="rattache_a_dos2j-container' . $rnd1 . '"></span><input type="hidden" name="rattache_a_dos2j" id="rattache_a_dos2j' . $rnd1 . '" value="' . html_attr($combo_rattache_a_dos2j->SelectedData) . '">';
	$combo_rattache_a_dos2j->MatchText = '<span id="rattache_a_dos2j-container-readonly' . $rnd1 . '"></span><input type="hidden" name="rattache_a_dos2j" id="rattache_a_dos2j' . $rnd1 . '" value="' . html_attr($combo_rattache_a_dos2j->SelectedData) . '">';
	$combo_rattache_a_seq->HTML = '<span id="rattache_a_seq-container' . $rnd1 . '"></span><input type="hidden" name="rattache_a_seq" id="rattache_a_seq' . $rnd1 . '" value="' . html_attr($combo_rattache_a_seq->SelectedData) . '">';
	$combo_rattache_a_seq->MatchText = '<span id="rattache_a_seq-container-readonly' . $rnd1 . '"></span><input type="hidden" name="rattache_a_seq" id="rattache_a_seq' . $rnd1 . '" value="' . html_attr($combo_rattache_a_seq->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_Contient__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['Contient'] : $filterer_Contient); ?>"};
		AppGini.current_rattache_a_dos2j__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['rattache_a_dos2j'] : $filterer_rattache_a_dos2j); ?>"};
		AppGini.current_rattache_a_seq__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['rattache_a_seq'] : $filterer_rattache_a_seq); ?>"};

		jQuery(function() {
			setTimeout(function(){
				if(typeof(Contient_reload__RAND__) == 'function') Contient_reload__RAND__();
				if(typeof(rattache_a_dos2j_reload__RAND__) == 'function') rattache_a_dos2j_reload__RAND__();
				if(typeof(rattache_a_seq_reload__RAND__) == 'function') rattache_a_seq_reload__RAND__();
			}, 10); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function Contient_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			$j("#Contient-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_Contient__RAND__.value, t: 'Objets', f: 'Contient' },
						success: function(resp){
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="Contient"]').val(resp.results[0].id);
							$j('[id=Contient-container-readonly__RAND__]').html('<span id="Contient-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=Objets_view_parent]').hide(); }else{ $j('.btn[id=Objets_view_parent]').show(); }


							if(typeof(Contient_update_autofills__RAND__) == 'function') Contient_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term){ /* */ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ /* */ return { s: term, p: page, t: 'Objets', f: 'Contient' }; },
					results: function(resp, page){ /* */ return resp; }
				},
				escapeMarkup: function(str){ /* */ return str; }
			}).on('change', function(e){
				AppGini.current_Contient__RAND__.value = e.added.id;
				AppGini.current_Contient__RAND__.text = e.added.text;
				$j('[name="Contient"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=Objets_view_parent]').hide(); }else{ $j('.btn[id=Objets_view_parent]').show(); }


				if(typeof(Contient_update_autofills__RAND__) == 'function') Contient_update_autofills__RAND__();
			});

			if(!$j("#Contient-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_Contient__RAND__.value, t: 'Objets', f: 'Contient' },
					success: function(resp){
						$j('[name="Contient"]').val(resp.results[0].id);
						$j('[id=Contient-container-readonly__RAND__]').html('<span id="Contient-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=Objets_view_parent]').hide(); }else{ $j('.btn[id=Objets_view_parent]').show(); }

						if(typeof(Contient_update_autofills__RAND__) == 'function') Contient_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_Contient__RAND__.value, t: 'Objets', f: 'Contient' },
				success: function(resp){
					$j('[id=Contient-container__RAND__], [id=Contient-container-readonly__RAND__]').html('<span id="Contient-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=Objets_view_parent]').hide(); }else{ $j('.btn[id=Objets_view_parent]').show(); }

					if(typeof(Contient_update_autofills__RAND__) == 'function') Contient_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function rattache_a_dos2j_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			$j("#rattache_a_dos2j-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_rattache_a_dos2j__RAND__.value, t: 'Objets', f: 'rattache_a_dos2j' },
						success: function(resp){
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="rattache_a_dos2j"]').val(resp.results[0].id);
							$j('[id=rattache_a_dos2j-container-readonly__RAND__]').html('<span id="rattache_a_dos2j-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=Dossier_histoire_view_parent]').hide(); }else{ $j('.btn[id=Dossier_histoire_view_parent]').show(); }


							if(typeof(rattache_a_dos2j_update_autofills__RAND__) == 'function') rattache_a_dos2j_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term){ /* */ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ /* */ return { s: term, p: page, t: 'Objets', f: 'rattache_a_dos2j' }; },
					results: function(resp, page){ /* */ return resp; }
				},
				escapeMarkup: function(str){ /* */ return str; }
			}).on('change', function(e){
				AppGini.current_rattache_a_dos2j__RAND__.value = e.added.id;
				AppGini.current_rattache_a_dos2j__RAND__.text = e.added.text;
				$j('[name="rattache_a_dos2j"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=Dossier_histoire_view_parent]').hide(); }else{ $j('.btn[id=Dossier_histoire_view_parent]').show(); }


				if(typeof(rattache_a_dos2j_update_autofills__RAND__) == 'function') rattache_a_dos2j_update_autofills__RAND__();
			});

			if(!$j("#rattache_a_dos2j-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_rattache_a_dos2j__RAND__.value, t: 'Objets', f: 'rattache_a_dos2j' },
					success: function(resp){
						$j('[name="rattache_a_dos2j"]').val(resp.results[0].id);
						$j('[id=rattache_a_dos2j-container-readonly__RAND__]').html('<span id="rattache_a_dos2j-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=Dossier_histoire_view_parent]').hide(); }else{ $j('.btn[id=Dossier_histoire_view_parent]').show(); }

						if(typeof(rattache_a_dos2j_update_autofills__RAND__) == 'function') rattache_a_dos2j_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_rattache_a_dos2j__RAND__.value, t: 'Objets', f: 'rattache_a_dos2j' },
				success: function(resp){
					$j('[id=rattache_a_dos2j-container__RAND__], [id=rattache_a_dos2j-container-readonly__RAND__]').html('<span id="rattache_a_dos2j-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=Dossier_histoire_view_parent]').hide(); }else{ $j('.btn[id=Dossier_histoire_view_parent]').show(); }

					if(typeof(rattache_a_dos2j_update_autofills__RAND__) == 'function') rattache_a_dos2j_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function rattache_a_seq_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			$j("#rattache_a_seq-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_rattache_a_seq__RAND__.value, t: 'Objets', f: 'rattache_a_seq' },
						success: function(resp){
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="rattache_a_seq"]').val(resp.results[0].id);
							$j('[id=rattache_a_seq-container-readonly__RAND__]').html('<span id="rattache_a_seq-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=sequence_view_parent]').hide(); }else{ $j('.btn[id=sequence_view_parent]').show(); }


							if(typeof(rattache_a_seq_update_autofills__RAND__) == 'function') rattache_a_seq_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term){ /* */ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ /* */ return { s: term, p: page, t: 'Objets', f: 'rattache_a_seq' }; },
					results: function(resp, page){ /* */ return resp; }
				},
				escapeMarkup: function(str){ /* */ return str; }
			}).on('change', function(e){
				AppGini.current_rattache_a_seq__RAND__.value = e.added.id;
				AppGini.current_rattache_a_seq__RAND__.text = e.added.text;
				$j('[name="rattache_a_seq"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=sequence_view_parent]').hide(); }else{ $j('.btn[id=sequence_view_parent]').show(); }


				if(typeof(rattache_a_seq_update_autofills__RAND__) == 'function') rattache_a_seq_update_autofills__RAND__();
			});

			if(!$j("#rattache_a_seq-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_rattache_a_seq__RAND__.value, t: 'Objets', f: 'rattache_a_seq' },
					success: function(resp){
						$j('[name="rattache_a_seq"]').val(resp.results[0].id);
						$j('[id=rattache_a_seq-container-readonly__RAND__]').html('<span id="rattache_a_seq-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=sequence_view_parent]').hide(); }else{ $j('.btn[id=sequence_view_parent]').show(); }

						if(typeof(rattache_a_seq_update_autofills__RAND__) == 'function') rattache_a_seq_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_rattache_a_seq__RAND__.value, t: 'Objets', f: 'rattache_a_seq' },
				success: function(resp){
					$j('[id=rattache_a_seq-container__RAND__], [id=rattache_a_seq-container-readonly__RAND__]').html('<span id="rattache_a_seq-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=sequence_view_parent]').hide(); }else{ $j('.btn[id=sequence_view_parent]').show(); }

					if(typeof(rattache_a_seq_update_autofills__RAND__) == 'function') rattache_a_seq_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	if($dvprint){
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/Objets_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	}else{
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/Objets_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Objet details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert){
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return Objets_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return Objets_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']){
		$backAction = 'AppGini.closeParentModal(); return false;';
	}else{
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id){
		if(!$_REQUEST['Embedded']) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate){
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return Objets_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)){
		$jsReadOnly .= "\tjQuery('#nom_objet').replaceWith('<div class=\"form-control-static\" id=\"nom_objet\">' + (jQuery('#nom_objet').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#illustration').replaceWith('<div class=\"form-control-static\" id=\"illustration\">' + (jQuery('#illustration').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#typologie').replaceWith('<div class=\"form-control-static\" id=\"typologie\">' + (jQuery('#typologie').val() || '') + '</div>'); jQuery('#typologie-multi-selection-help').hide();\n";
		$jsReadOnly .= "\tjQuery('#Contient').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#Contient_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#rattache_a_dos2j').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#rattache_a_dos2j_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#rattache_a_seq').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#rattache_a_seq_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	}elseif($AllowInsert){
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(typologie)%%>', $combo_typologie->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(typologie)%%>', $combo_typologie->SelectedData, $templateCode);
	$templateCode = str_replace('<%%COMBO(Contient)%%>', $combo_Contient->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Contient)%%>', $combo_Contient->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(Contient)%%>', urlencode($combo_Contient->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(rattache_a_dos2j)%%>', $combo_rattache_a_dos2j->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(rattache_a_dos2j)%%>', $combo_rattache_a_dos2j->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(rattache_a_dos2j)%%>', urlencode($combo_rattache_a_dos2j->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(rattache_a_seq)%%>', $combo_rattache_a_seq->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(rattache_a_seq)%%>', $combo_rattache_a_seq->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(rattache_a_seq)%%>', urlencode($combo_rattache_a_seq->MatchText), $templateCode);

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array(  'Contient' => array('Objets', 'Contient'), 'rattache_a_dos2j' => array('Dossier_histoire', 'Rattache a dos2j'), 'rattache_a_seq' => array('sequence', 'Rattache a seq'));
	foreach($lookup_fields as $luf => $ptfc){
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']){
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] && !$_REQUEST['Embedded']){
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id_objet)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(nom_objet)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(illustration)%%>', ($noUploads ? '' : '<input type=hidden name=MAX_FILE_SIZE value=102400>'.$Translation['upload image'].' <input type="file" name="illustration" id="illustration">'), $templateCode);
	if($AllowUpdate && $row['illustration'] != ''){
		$templateCode = str_replace('<%%REMOVEFILE(illustration)%%>', '<br><input type="checkbox" name="illustration_remove" id="illustration_remove" value="1"> <label for="illustration_remove" style="color: red; font-weight: bold;">'.$Translation['remove image'].'</label>', $templateCode);
	}else{
		$templateCode = str_replace('<%%REMOVEFILE(illustration)%%>', '', $templateCode);
	}
	$templateCode = str_replace('<%%UPLOADFILE(typologie)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Aquoisertil)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Contient)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(creer_par)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(rattache_a_dos2j)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(rattache_a_seq)%%>', '', $templateCode);

	// process values
	if($selected_id){
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id_objet)%%>', safe_html($urow['id_objet']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id_objet)%%>', html_attr($row['id_objet']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id_objet)%%>', urlencode($urow['id_objet']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(nom_objet)%%>', safe_html($urow['nom_objet']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(nom_objet)%%>', html_attr($row['nom_objet']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(nom_objet)%%>', urlencode($urow['nom_objet']), $templateCode);
		$row['illustration'] = ($row['illustration'] != '' ? $row['illustration'] : 'blank.gif');
		if( $dvprint) $templateCode = str_replace('<%%VALUE(illustration)%%>', safe_html($urow['illustration']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(illustration)%%>', html_attr($row['illustration']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(illustration)%%>', urlencode($urow['illustration']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(typologie)%%>', safe_html($urow['typologie']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(typologie)%%>', html_attr($row['typologie']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(typologie)%%>', urlencode($urow['typologie']), $templateCode);
		if($AllowUpdate || $AllowInsert){
			$templateCode = str_replace('<%%HTMLAREA(Aquoisertil)%%>', '<textarea name="Aquoisertil" id="Aquoisertil" rows="5">' . html_attr($row['Aquoisertil']) . '</textarea>', $templateCode);
		}else{
			$templateCode = str_replace('<%%HTMLAREA(Aquoisertil)%%>', '<div id="Aquoisertil" class="form-control-static">' . $row['Aquoisertil'] . '</div>', $templateCode);
		}
		$templateCode = str_replace('<%%VALUE(Aquoisertil)%%>', nl2br($row['Aquoisertil']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Aquoisertil)%%>', urlencode($urow['Aquoisertil']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Contient)%%>', safe_html($urow['Contient']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Contient)%%>', html_attr($row['Contient']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Contient)%%>', urlencode($urow['Contient']), $templateCode);
		$templateCode = str_replace('<%%VALUE(creer_par)%%>', safe_html($urow['creer_par']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(creer_par)%%>', urlencode($urow['creer_par']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(rattache_a_dos2j)%%>', safe_html($urow['rattache_a_dos2j']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(rattache_a_dos2j)%%>', html_attr($row['rattache_a_dos2j']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(rattache_a_dos2j)%%>', urlencode($urow['rattache_a_dos2j']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(rattache_a_seq)%%>', safe_html($urow['rattache_a_seq']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(rattache_a_seq)%%>', html_attr($row['rattache_a_seq']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(rattache_a_seq)%%>', urlencode($urow['rattache_a_seq']), $templateCode);
	}else{
		$templateCode = str_replace('<%%VALUE(id_objet)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id_objet)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(nom_objet)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(nom_objet)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(illustration)%%>', 'blank.gif', $templateCode);
		$templateCode = str_replace('<%%VALUE(typologie)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(typologie)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%HTMLAREA(Aquoisertil)%%>', '<textarea name="Aquoisertil" id="Aquoisertil" rows="5"></textarea>', $templateCode);
		$templateCode = str_replace('<%%VALUE(Contient)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Contient)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(creer_par)%%>', '<%%creatorUsername%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(creer_par)%%>', urlencode('<%%creatorUsername%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(rattache_a_dos2j)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(rattache_a_dos2j)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(rattache_a_seq)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(rattache_a_seq)%%>', urlencode(''), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode = str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == ''){
		$templateCode .= "\n\n<script>\$j(function(){\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption){
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id){
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('Objets');
	if($selected_id){
		$jdata = get_joined_record('Objets', $selected_id);
		if($jdata === false) $jdata = get_defaults('Objets');
		$rdata = $row;
	}
	$templateCode .= loadView('Objets-ajax-cache', array('rdata' => $rdata, 'jdata' => $jdata));

	// hook: Objets_dv
	if(function_exists('Objets_dv')){
		$args=array();
		Objets_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>