<?php
// This script and data application were generated by AppGini 5.75
// Download AppGini for free from https://bigprof.com/appgini/download/

	/* Configuration */
	/*************************************/

		$pcConfig = array(
			'redacteur' => array(   
			),
			'Dossier_histoire' => array(   
			),
			'chapitre' => array(   
				'rattache_a_dossier' => array(   
					'parent-table' => 'Dossier_histoire',
					'parent-primary-key' => 'id2dossier',
					'child-primary-key' => 'id',
					'child-primary-key-index' => 0,
					'tab-label' => 'Scenario <span class="hidden child-label-chapitre child-field-caption">(Rattache a dossier)</span>',
					'auto-close' => false,
					'table-icon' => 'resources/table_icons/align_right.png',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => array(1 => 'Titre', 2 => 'Mission', 3 => 'Resume', 4 => 'Rattache a dossier', 5 => 'Auteur'),
					'display-field-names' => array(1 => 'titre', 2 => 'Mission', 3 => 'resume', 4 => 'rattache_a_dossier', 5 => 'auteur'),
					'sortable-fields' => array(0 => '`chapitre`.`id`', 1 => 2, 2 => 3, 3 => 4, 4 => '`Dossier_histoire1`.`titre_histoire`', 5 => 6),
					'records-per-page' => 10,
					'default-sort-by' => false,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-chapitre',
					'template-printable' => 'children-chapitre-printable',
					'query' => "SELECT `chapitre`.`id` as 'id', `chapitre`.`titre` as 'titre', IF(    CHAR_LENGTH(`ref_mission1`.`titre`) || CHAR_LENGTH(`ref_mission1`.`description`), CONCAT_WS('',   `ref_mission1`.`titre`, ' : ', `ref_mission1`.`description`), '') as 'Mission', `chapitre`.`resume` as 'resume', IF(    CHAR_LENGTH(`Dossier_histoire1`.`titre_histoire`), CONCAT_WS('',   `Dossier_histoire1`.`titre_histoire`), '') as 'rattache_a_dossier', `chapitre`.`auteur` as 'auteur' FROM `chapitre` LEFT JOIN `ref_mission` as ref_mission1 ON `ref_mission1`.`id_misref`=`chapitre`.`Mission` LEFT JOIN `Dossier_histoire` as Dossier_histoire1 ON `Dossier_histoire1`.`id2dossier`=`chapitre`.`rattache_a_dossier` "
				)
			),
			'sequence' => array(   
				'rattache_a_chapitre' => array(   
					'parent-table' => 'chapitre',
					'parent-primary-key' => 'id',
					'child-primary-key' => 'id_sequence',
					'child-primary-key-index' => 0,
					'tab-label' => 'Sequences <span class="hidden child-label-sequence child-field-caption">(Rattach&#233; au chapitre)</span>',
					'auto-close' => false,
					'table-icon' => 'resources/table_icons/attributes_display.png',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => array(1 => 'Numero de la s&#233;quence', 2 => 'Titre', 4 => 'Difficulte', 5 => 'Description', 7 => 'Modele'),
					'display-field-names' => array(1 => 'numero_ordre', 2 => 'titre', 4 => 'difficulte', 5 => 'description', 7 => 'modele'),
					'sortable-fields' => array(0 => '`sequence`.`id_sequence`', 1 => '`sequence`.`numero_ordre`', 2 => 3, 3 => '`chapitre1`.`titre`', 4 => 5, 5 => 6, 6 => 7, 7 => 8),
					'records-per-page' => 10,
					'default-sort-by' => 1,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-sequence',
					'template-printable' => 'children-sequence-printable',
					'query' => "SELECT `sequence`.`id_sequence` as 'id_sequence', `sequence`.`numero_ordre` as 'numero_ordre', `sequence`.`titre` as 'titre', IF(    CHAR_LENGTH(`chapitre1`.`titre`), CONCAT_WS('',   `chapitre1`.`titre`), '') as 'rattache_a_chapitre', `sequence`.`difficulte` as 'difficulte', `sequence`.`description` as 'description', `sequence`.`auteur` as 'auteur', IF(    CHAR_LENGTH(`ref_sequences1`.`typologie`) || CHAR_LENGTH(`ref_sequences1`.`titre`), CONCAT_WS('',   `ref_sequences1`.`typologie`, ' : ', `ref_sequences1`.`titre`), '') as 'modele' FROM `sequence` LEFT JOIN `chapitre` as chapitre1 ON `chapitre1`.`id`=`sequence`.`rattache_a_chapitre` LEFT JOIN `ref_sequences` as ref_sequences1 ON `ref_sequences1`.`id_seqref`=`sequence`.`modele` "
				)
			),
			'Objectifs' => array(   
				'rattache_a_dos2j' => array(   
					'parent-table' => 'Dossier_histoire',
					'parent-primary-key' => 'id2dossier',
					'child-primary-key' => 'id_objectif',
					'child-primary-key-index' => 0,
					'tab-label' => 'Objectifs <span class="hidden child-label-Objectifs child-field-caption">(Rattache a dos2j)</span>',
					'auto-close' => false,
					'table-icon' => 'resources/table_icons/compass.png',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => array(1 => 'Titre de l\'objectif', 2 => 'Description obj', 3 => 'Gameplay'),
					'display-field-names' => array(1 => 'titreobj', 2 => 'description_obj', 3 => 'ref_o_gameplay'),
					'sortable-fields' => array(0 => '`Objectifs`.`id_objectif`', 1 => 2, 2 => 3, 3 => 4, 4 => 5, 5 => '`Dossier_histoire1`.`titre_histoire`'),
					'records-per-page' => 10,
					'default-sort-by' => false,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-Objectifs',
					'template-printable' => 'children-Objectifs-printable',
					'query' => "SELECT `Objectifs`.`id_objectif` as 'id_objectif', if(CHAR_LENGTH(`Objectifs`.`titreobj`)>64, concat(left(`Objectifs`.`titreobj`,64),' ...'), `Objectifs`.`titreobj`) as 'titreobj', `Objectifs`.`description_obj` as 'description_obj', `Objectifs`.`ref_o_gameplay` as 'ref_o_gameplay', `Objectifs`.`creer_par` as 'creer_par', IF(    CHAR_LENGTH(`Dossier_histoire1`.`titre_histoire`), CONCAT_WS('',   `Dossier_histoire1`.`titre_histoire`), '') as 'rattache_a_dos2j' FROM `Objectifs` LEFT JOIN `Dossier_histoire` as Dossier_histoire1 ON `Dossier_histoire1`.`id2dossier`=`Objectifs`.`rattache_a_dos2j` "
				)
			),
			'moyens' => array(   
				'rattache_a_dos2j' => array(   
					'parent-table' => 'Dossier_histoire',
					'parent-primary-key' => 'id2dossier',
					'child-primary-key' => 'id_moyen',
					'child-primary-key-index' => 0,
					'tab-label' => 'Moyens <span class="hidden child-label-moyens child-field-caption">(Rattache a dos2j)</span>',
					'auto-close' => false,
					'table-icon' => 'resources/table_icons/brick.png',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => array(1 => 'Moyen du joueur', 2 => 'Description du moyen', 3 => 'Gameplay'),
					'display-field-names' => array(1 => 'titremoy', 2 => 'description_moy', 3 => 'ref_o_gameplay'),
					'sortable-fields' => array(0 => '`moyens`.`id_moyen`', 1 => 2, 2 => 3, 3 => 4, 4 => 5, 5 => '`Dossier_histoire1`.`titre_histoire`'),
					'records-per-page' => 10,
					'default-sort-by' => false,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-moyens',
					'template-printable' => 'children-moyens-printable',
					'query' => "SELECT `moyens`.`id_moyen` as 'id_moyen', if(CHAR_LENGTH(`moyens`.`titremoy`)>64, concat(left(`moyens`.`titremoy`,64),' ...'), `moyens`.`titremoy`) as 'titremoy', `moyens`.`description_moy` as 'description_moy', `moyens`.`ref_o_gameplay` as 'ref_o_gameplay', `moyens`.`creer_par` as 'creer_par', IF(    CHAR_LENGTH(`Dossier_histoire1`.`titre_histoire`), CONCAT_WS('',   `Dossier_histoire1`.`titre_histoire`), '') as 'rattache_a_dos2j' FROM `moyens` LEFT JOIN `Dossier_histoire` as Dossier_histoire1 ON `Dossier_histoire1`.`id2dossier`=`moyens`.`rattache_a_dos2j` "
				)
			),
			'Objets' => array(   
				'Contient' => array(   
					'parent-table' => 'Objets',
					'parent-primary-key' => 'id_objet',
					'child-primary-key' => 'id_objet',
					'child-primary-key-index' => 0,
					'tab-label' => 'Objets <span class="hidden child-label-Objets child-field-caption">(Contient)</span>',
					'auto-close' => true,
					'table-icon' => 'resources/table_icons/color_swatch.png',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => array(1 => 'Nom objet', 2 => 'Illustration', 3 => 'Typologie', 4 => 'A quoi sert il'),
					'display-field-names' => array(1 => 'nom_objet', 2 => 'illustration', 3 => 'typologie', 4 => 'Aquoisertil'),
					'sortable-fields' => array(0 => '`Objets`.`id_objet`', 1 => 2, 2 => 3, 3 => 4, 4 => 5, 5 => 6, 6 => 7, 7 => '`Dossier_histoire1`.`titre_histoire`', 8 => 9),
					'records-per-page' => 10,
					'default-sort-by' => false,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-Objets',
					'template-printable' => 'children-Objets-printable',
					'query' => "SELECT `Objets`.`id_objet` as 'id_objet', `Objets`.`nom_objet` as 'nom_objet', `Objets`.`illustration` as 'illustration', `Objets`.`typologie` as 'typologie', `Objets`.`Aquoisertil` as 'Aquoisertil', IF(    CHAR_LENGTH(`Objets1`.`nom_objet`) || CHAR_LENGTH(`Objets1`.`illustration`), CONCAT_WS('',   `Objets1`.`nom_objet`, `Objets1`.`illustration`), '') as 'Contient', `Objets`.`creer_par` as 'creer_par', IF(    CHAR_LENGTH(`Dossier_histoire1`.`titre_histoire`), CONCAT_WS('',   `Dossier_histoire1`.`titre_histoire`), '') as 'rattache_a_dos2j', IF(    CHAR_LENGTH(`sequence1`.`numero_ordre`) || CHAR_LENGTH(`sequence1`.`titre`), CONCAT_WS('',   `sequence1`.`numero_ordre`, ' ', `sequence1`.`titre`), '') as 'rattache_a_seq' FROM `Objets` LEFT JOIN `Objets` as Objets1 ON `Objets1`.`id_objet`=`Objets`.`Contient` LEFT JOIN `Dossier_histoire` as Dossier_histoire1 ON `Dossier_histoire1`.`id2dossier`=`Objets`.`rattache_a_dos2j` LEFT JOIN `sequence` as sequence1 ON `sequence1`.`id_sequence`=`Objets`.`rattache_a_seq` "
				),
				'rattache_a_dos2j' => array(   
					'parent-table' => 'Dossier_histoire',
					'parent-primary-key' => 'id2dossier',
					'child-primary-key' => 'id_objet',
					'child-primary-key-index' => 0,
					'tab-label' => 'Objets <span class="hidden child-label-Objets child-field-caption">(Rattache a dos2j)</span>',
					'auto-close' => false,
					'table-icon' => 'resources/table_icons/color_swatch.png',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => array(1 => 'Nom objet', 2 => 'Illustration', 3 => 'Typologie', 4 => 'A quoi sert il'),
					'display-field-names' => array(1 => 'nom_objet', 2 => 'illustration', 3 => 'typologie', 4 => 'Aquoisertil'),
					'sortable-fields' => array(0 => '`Objets`.`id_objet`', 1 => 2, 2 => 3, 3 => 4, 4 => 5, 5 => 6, 6 => 7, 7 => '`Dossier_histoire1`.`titre_histoire`', 8 => 9),
					'records-per-page' => 10,
					'default-sort-by' => false,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-Objets',
					'template-printable' => 'children-Objets-printable',
					'query' => "SELECT `Objets`.`id_objet` as 'id_objet', `Objets`.`nom_objet` as 'nom_objet', `Objets`.`illustration` as 'illustration', `Objets`.`typologie` as 'typologie', `Objets`.`Aquoisertil` as 'Aquoisertil', IF(    CHAR_LENGTH(`Objets1`.`nom_objet`) || CHAR_LENGTH(`Objets1`.`illustration`), CONCAT_WS('',   `Objets1`.`nom_objet`, `Objets1`.`illustration`), '') as 'Contient', `Objets`.`creer_par` as 'creer_par', IF(    CHAR_LENGTH(`Dossier_histoire1`.`titre_histoire`), CONCAT_WS('',   `Dossier_histoire1`.`titre_histoire`), '') as 'rattache_a_dos2j', IF(    CHAR_LENGTH(`sequence1`.`numero_ordre`) || CHAR_LENGTH(`sequence1`.`titre`), CONCAT_WS('',   `sequence1`.`numero_ordre`, ' ', `sequence1`.`titre`), '') as 'rattache_a_seq' FROM `Objets` LEFT JOIN `Objets` as Objets1 ON `Objets1`.`id_objet`=`Objets`.`Contient` LEFT JOIN `Dossier_histoire` as Dossier_histoire1 ON `Dossier_histoire1`.`id2dossier`=`Objets`.`rattache_a_dos2j` LEFT JOIN `sequence` as sequence1 ON `sequence1`.`id_sequence`=`Objets`.`rattache_a_seq` "
				),
				'rattache_a_seq' => array(   
					'parent-table' => 'sequence',
					'parent-primary-key' => 'id_sequence',
					'child-primary-key' => 'id_objet',
					'child-primary-key-index' => 0,
					'tab-label' => 'Objets <span class="hidden child-label-Objets child-field-caption">(Rattache a seq)</span>',
					'auto-close' => false,
					'table-icon' => 'resources/table_icons/color_swatch.png',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => array(1 => 'Nom objet', 2 => 'Illustration', 3 => 'Typologie', 4 => 'A quoi sert il'),
					'display-field-names' => array(1 => 'nom_objet', 2 => 'illustration', 3 => 'typologie', 4 => 'Aquoisertil'),
					'sortable-fields' => array(0 => '`Objets`.`id_objet`', 1 => 2, 2 => 3, 3 => 4, 4 => 5, 5 => 6, 6 => 7, 7 => '`Dossier_histoire1`.`titre_histoire`', 8 => 9),
					'records-per-page' => 10,
					'default-sort-by' => false,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-Objets',
					'template-printable' => 'children-Objets-printable',
					'query' => "SELECT `Objets`.`id_objet` as 'id_objet', `Objets`.`nom_objet` as 'nom_objet', `Objets`.`illustration` as 'illustration', `Objets`.`typologie` as 'typologie', `Objets`.`Aquoisertil` as 'Aquoisertil', IF(    CHAR_LENGTH(`Objets1`.`nom_objet`) || CHAR_LENGTH(`Objets1`.`illustration`), CONCAT_WS('',   `Objets1`.`nom_objet`, `Objets1`.`illustration`), '') as 'Contient', `Objets`.`creer_par` as 'creer_par', IF(    CHAR_LENGTH(`Dossier_histoire1`.`titre_histoire`), CONCAT_WS('',   `Dossier_histoire1`.`titre_histoire`), '') as 'rattache_a_dos2j', IF(    CHAR_LENGTH(`sequence1`.`numero_ordre`) || CHAR_LENGTH(`sequence1`.`titre`), CONCAT_WS('',   `sequence1`.`numero_ordre`, ' ', `sequence1`.`titre`), '') as 'rattache_a_seq' FROM `Objets` LEFT JOIN `Objets` as Objets1 ON `Objets1`.`id_objet`=`Objets`.`Contient` LEFT JOIN `Dossier_histoire` as Dossier_histoire1 ON `Dossier_histoire1`.`id2dossier`=`Objets`.`rattache_a_dos2j` LEFT JOIN `sequence` as sequence1 ON `sequence1`.`id_sequence`=`Objets`.`rattache_a_seq` "
				)
			),
			'personnages' => array(   
				'quepossedetil' => array(   
					'parent-table' => 'Objets',
					'parent-primary-key' => 'id_objet',
					'child-primary-key' => 'id_perso',
					'child-primary-key-index' => 0,
					'tab-label' => 'Personnages <span class="hidden child-label-personnages child-field-caption">(Que possede-t-il ?)</span>',
					'auto-close' => false,
					'table-icon' => 'resources/table_icons/client_account_template.png',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => array(1 => 'Nom', 2 => 'Type', 3 => 'Illustration', 4 => 'Description', 5 => 'Que possede-t-il ?'),
					'display-field-names' => array(1 => 'nom', 2 => 'type', 3 => 'illustration', 4 => 'description', 5 => 'quepossedetil'),
					'sortable-fields' => array(0 => '`personnages`.`id_perso`', 1 => 2, 2 => 3, 3 => 4, 4 => 5, 5 => 6, 6 => 7, 7 => 8, 8 => 9, 9 => '`Dossier_histoire1`.`titre_histoire`', 10 => 11),
					'records-per-page' => 10,
					'default-sort-by' => false,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-personnages',
					'template-printable' => 'children-personnages-printable',
					'query' => "SELECT `personnages`.`id_perso` as 'id_perso', `personnages`.`nom` as 'nom', `personnages`.`type` as 'type', `personnages`.`illustration` as 'illustration', `personnages`.`description` as 'description', IF(    CHAR_LENGTH(`Objets1`.`nom_objet`) || CHAR_LENGTH(`Objets1`.`illustration`), CONCAT_WS('',   `Objets1`.`nom_objet`, `Objets1`.`illustration`), '') as 'quepossedetil', `personnages`.`apparait_quand` as 'apparait_quand', `personnages`.`disparait_quand` as 'disparait_quand', `personnages`.`creer_par` as 'creer_par', IF(    CHAR_LENGTH(`Dossier_histoire1`.`titre_histoire`), CONCAT_WS('',   `Dossier_histoire1`.`titre_histoire`), '') as 'rattache_a_dos2j', IF(    CHAR_LENGTH(`sequence1`.`numero_ordre`) || CHAR_LENGTH(`sequence1`.`titre`), CONCAT_WS('',   `sequence1`.`numero_ordre`, ' ', `sequence1`.`titre`), '') as 'rattache_a_seq' FROM `personnages` LEFT JOIN `Objets` as Objets1 ON `Objets1`.`id_objet`=`personnages`.`quepossedetil` LEFT JOIN `Dossier_histoire` as Dossier_histoire1 ON `Dossier_histoire1`.`id2dossier`=`personnages`.`rattache_a_dos2j` LEFT JOIN `sequence` as sequence1 ON `sequence1`.`id_sequence`=`personnages`.`rattache_a_seq` "
				),
				'rattache_a_dos2j' => array(   
					'parent-table' => 'Dossier_histoire',
					'parent-primary-key' => 'id2dossier',
					'child-primary-key' => 'id_perso',
					'child-primary-key-index' => 0,
					'tab-label' => 'Personnages <span class="hidden child-label-personnages child-field-caption">(Rattache a dos2j)</span>',
					'auto-close' => false,
					'table-icon' => 'resources/table_icons/client_account_template.png',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => array(1 => 'Nom', 2 => 'Type', 3 => 'Illustration', 4 => 'Description', 5 => 'Que possede-t-il ?'),
					'display-field-names' => array(1 => 'nom', 2 => 'type', 3 => 'illustration', 4 => 'description', 5 => 'quepossedetil'),
					'sortable-fields' => array(0 => '`personnages`.`id_perso`', 1 => 2, 2 => 3, 3 => 4, 4 => 5, 5 => 6, 6 => 7, 7 => 8, 8 => 9, 9 => '`Dossier_histoire1`.`titre_histoire`', 10 => 11),
					'records-per-page' => 10,
					'default-sort-by' => false,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-personnages',
					'template-printable' => 'children-personnages-printable',
					'query' => "SELECT `personnages`.`id_perso` as 'id_perso', `personnages`.`nom` as 'nom', `personnages`.`type` as 'type', `personnages`.`illustration` as 'illustration', `personnages`.`description` as 'description', IF(    CHAR_LENGTH(`Objets1`.`nom_objet`) || CHAR_LENGTH(`Objets1`.`illustration`), CONCAT_WS('',   `Objets1`.`nom_objet`, `Objets1`.`illustration`), '') as 'quepossedetil', `personnages`.`apparait_quand` as 'apparait_quand', `personnages`.`disparait_quand` as 'disparait_quand', `personnages`.`creer_par` as 'creer_par', IF(    CHAR_LENGTH(`Dossier_histoire1`.`titre_histoire`), CONCAT_WS('',   `Dossier_histoire1`.`titre_histoire`), '') as 'rattache_a_dos2j', IF(    CHAR_LENGTH(`sequence1`.`numero_ordre`) || CHAR_LENGTH(`sequence1`.`titre`), CONCAT_WS('',   `sequence1`.`numero_ordre`, ' ', `sequence1`.`titre`), '') as 'rattache_a_seq' FROM `personnages` LEFT JOIN `Objets` as Objets1 ON `Objets1`.`id_objet`=`personnages`.`quepossedetil` LEFT JOIN `Dossier_histoire` as Dossier_histoire1 ON `Dossier_histoire1`.`id2dossier`=`personnages`.`rattache_a_dos2j` LEFT JOIN `sequence` as sequence1 ON `sequence1`.`id_sequence`=`personnages`.`rattache_a_seq` "
				),
				'rattache_a_seq' => array(   
					'parent-table' => 'sequence',
					'parent-primary-key' => 'id_sequence',
					'child-primary-key' => 'id_perso',
					'child-primary-key-index' => 0,
					'tab-label' => 'Personnages <span class="hidden child-label-personnages child-field-caption">(Rattache a seq)</span>',
					'auto-close' => false,
					'table-icon' => 'resources/table_icons/client_account_template.png',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => array(1 => 'Nom', 2 => 'Type', 3 => 'Illustration', 4 => 'Description', 5 => 'Que possede-t-il ?'),
					'display-field-names' => array(1 => 'nom', 2 => 'type', 3 => 'illustration', 4 => 'description', 5 => 'quepossedetil'),
					'sortable-fields' => array(0 => '`personnages`.`id_perso`', 1 => 2, 2 => 3, 3 => 4, 4 => 5, 5 => 6, 6 => 7, 7 => 8, 8 => 9, 9 => '`Dossier_histoire1`.`titre_histoire`', 10 => 11),
					'records-per-page' => 10,
					'default-sort-by' => false,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-personnages',
					'template-printable' => 'children-personnages-printable',
					'query' => "SELECT `personnages`.`id_perso` as 'id_perso', `personnages`.`nom` as 'nom', `personnages`.`type` as 'type', `personnages`.`illustration` as 'illustration', `personnages`.`description` as 'description', IF(    CHAR_LENGTH(`Objets1`.`nom_objet`) || CHAR_LENGTH(`Objets1`.`illustration`), CONCAT_WS('',   `Objets1`.`nom_objet`, `Objets1`.`illustration`), '') as 'quepossedetil', `personnages`.`apparait_quand` as 'apparait_quand', `personnages`.`disparait_quand` as 'disparait_quand', `personnages`.`creer_par` as 'creer_par', IF(    CHAR_LENGTH(`Dossier_histoire1`.`titre_histoire`), CONCAT_WS('',   `Dossier_histoire1`.`titre_histoire`), '') as 'rattache_a_dos2j', IF(    CHAR_LENGTH(`sequence1`.`numero_ordre`) || CHAR_LENGTH(`sequence1`.`titre`), CONCAT_WS('',   `sequence1`.`numero_ordre`, ' ', `sequence1`.`titre`), '') as 'rattache_a_seq' FROM `personnages` LEFT JOIN `Objets` as Objets1 ON `Objets1`.`id_objet`=`personnages`.`quepossedetil` LEFT JOIN `Dossier_histoire` as Dossier_histoire1 ON `Dossier_histoire1`.`id2dossier`=`personnages`.`rattache_a_dos2j` LEFT JOIN `sequence` as sequence1 ON `sequence1`.`id_sequence`=`personnages`.`rattache_a_seq` "
				)
			),
			'lieu_et_scene' => array(   
				'objet_present' => array(   
					'parent-table' => 'Objets',
					'parent-primary-key' => 'id_objet',
					'child-primary-key' => 'id_lets',
					'child-primary-key-index' => 0,
					'tab-label' => 'Lieu et scene <span class="hidden child-label-lieu_et_scene child-field-caption">(Objet present)</span>',
					'auto-close' => false,
					'table-icon' => 'resources/table_icons/application_view_gallery.png',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => array(1 => 'Nom du lieu', 2 => 'Illustration', 3 => 'Description', 4 => 'Difficulte nivo'),
					'display-field-names' => array(1 => 'nom_du_lieu', 2 => 'illustration', 3 => 'description', 4 => 'difficulte_nivo'),
					'sortable-fields' => array(0 => '`lieu_et_scene`.`id_lets`', 1 => 2, 2 => 3, 3 => 4, 4 => 5, 5 => 6, 6 => 7, 7 => 8, 8 => 9, 9 => 10, 10 => '`Dossier_histoire1`.`titre_histoire`', 11 => 12),
					'records-per-page' => 10,
					'default-sort-by' => false,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-lieu_et_scene',
					'template-printable' => 'children-lieu_et_scene-printable',
					'query' => "SELECT `lieu_et_scene`.`id_lets` as 'id_lets', `lieu_et_scene`.`nom_du_lieu` as 'nom_du_lieu', `lieu_et_scene`.`illustration` as 'illustration', `lieu_et_scene`.`description` as 'description', `lieu_et_scene`.`difficulte_nivo` as 'difficulte_nivo', `lieu_et_scene`.`condition_entree` as 'condition_entree', `lieu_et_scene`.`condition_sortie` as 'condition_sortie', IF(    CHAR_LENGTH(`Objets1`.`nom_objet`) || CHAR_LENGTH(`Objets1`.`illustration`), CONCAT_WS('',   `Objets1`.`nom_objet`, `Objets1`.`illustration`), '') as 'objet_present', IF(    CHAR_LENGTH(`personnages1`.`nom`) || CHAR_LENGTH(`personnages1`.`illustration`), CONCAT_WS('',   `personnages1`.`nom`, `personnages1`.`illustration`), '') as 'persos_present', `lieu_et_scene`.`creer_par` as 'creer_par', IF(    CHAR_LENGTH(`Dossier_histoire1`.`titre_histoire`), CONCAT_WS('',   `Dossier_histoire1`.`titre_histoire`), '') as 'rattache_a_dos2j', IF(    CHAR_LENGTH(`sequence1`.`numero_ordre`) || CHAR_LENGTH(`sequence1`.`titre`), CONCAT_WS('',   `sequence1`.`numero_ordre`, ' ', `sequence1`.`titre`), '') as 'rattache_a_seq' FROM `lieu_et_scene` LEFT JOIN `Objets` as Objets1 ON `Objets1`.`id_objet`=`lieu_et_scene`.`objet_present` LEFT JOIN `personnages` as personnages1 ON `personnages1`.`id_perso`=`lieu_et_scene`.`persos_present` LEFT JOIN `Dossier_histoire` as Dossier_histoire1 ON `Dossier_histoire1`.`id2dossier`=`lieu_et_scene`.`rattache_a_dos2j` LEFT JOIN `sequence` as sequence1 ON `sequence1`.`id_sequence`=`lieu_et_scene`.`rattache_a_seq` "
				),
				'persos_present' => array(   
					'parent-table' => 'personnages',
					'parent-primary-key' => 'id_perso',
					'child-primary-key' => 'id_lets',
					'child-primary-key-index' => 0,
					'tab-label' => 'Lieu et scene <span class="hidden child-label-lieu_et_scene child-field-caption">(Persos present)</span>',
					'auto-close' => false,
					'table-icon' => 'resources/table_icons/application_view_gallery.png',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => array(1 => 'Nom du lieu', 2 => 'Illustration', 3 => 'Description', 4 => 'Difficulte nivo'),
					'display-field-names' => array(1 => 'nom_du_lieu', 2 => 'illustration', 3 => 'description', 4 => 'difficulte_nivo'),
					'sortable-fields' => array(0 => '`lieu_et_scene`.`id_lets`', 1 => 2, 2 => 3, 3 => 4, 4 => 5, 5 => 6, 6 => 7, 7 => 8, 8 => 9, 9 => 10, 10 => '`Dossier_histoire1`.`titre_histoire`', 11 => 12),
					'records-per-page' => 10,
					'default-sort-by' => false,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-lieu_et_scene',
					'template-printable' => 'children-lieu_et_scene-printable',
					'query' => "SELECT `lieu_et_scene`.`id_lets` as 'id_lets', `lieu_et_scene`.`nom_du_lieu` as 'nom_du_lieu', `lieu_et_scene`.`illustration` as 'illustration', `lieu_et_scene`.`description` as 'description', `lieu_et_scene`.`difficulte_nivo` as 'difficulte_nivo', `lieu_et_scene`.`condition_entree` as 'condition_entree', `lieu_et_scene`.`condition_sortie` as 'condition_sortie', IF(    CHAR_LENGTH(`Objets1`.`nom_objet`) || CHAR_LENGTH(`Objets1`.`illustration`), CONCAT_WS('',   `Objets1`.`nom_objet`, `Objets1`.`illustration`), '') as 'objet_present', IF(    CHAR_LENGTH(`personnages1`.`nom`) || CHAR_LENGTH(`personnages1`.`illustration`), CONCAT_WS('',   `personnages1`.`nom`, `personnages1`.`illustration`), '') as 'persos_present', `lieu_et_scene`.`creer_par` as 'creer_par', IF(    CHAR_LENGTH(`Dossier_histoire1`.`titre_histoire`), CONCAT_WS('',   `Dossier_histoire1`.`titre_histoire`), '') as 'rattache_a_dos2j', IF(    CHAR_LENGTH(`sequence1`.`numero_ordre`) || CHAR_LENGTH(`sequence1`.`titre`), CONCAT_WS('',   `sequence1`.`numero_ordre`, ' ', `sequence1`.`titre`), '') as 'rattache_a_seq' FROM `lieu_et_scene` LEFT JOIN `Objets` as Objets1 ON `Objets1`.`id_objet`=`lieu_et_scene`.`objet_present` LEFT JOIN `personnages` as personnages1 ON `personnages1`.`id_perso`=`lieu_et_scene`.`persos_present` LEFT JOIN `Dossier_histoire` as Dossier_histoire1 ON `Dossier_histoire1`.`id2dossier`=`lieu_et_scene`.`rattache_a_dos2j` LEFT JOIN `sequence` as sequence1 ON `sequence1`.`id_sequence`=`lieu_et_scene`.`rattache_a_seq` "
				),
				'rattache_a_dos2j' => array(   
					'parent-table' => 'Dossier_histoire',
					'parent-primary-key' => 'id2dossier',
					'child-primary-key' => 'id_lets',
					'child-primary-key-index' => 0,
					'tab-label' => 'Lieu et scene <span class="hidden child-label-lieu_et_scene child-field-caption">(Rattache a dos2j)</span>',
					'auto-close' => false,
					'table-icon' => 'resources/table_icons/application_view_gallery.png',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => array(1 => 'Nom du lieu', 2 => 'Illustration', 3 => 'Description', 4 => 'Difficulte nivo'),
					'display-field-names' => array(1 => 'nom_du_lieu', 2 => 'illustration', 3 => 'description', 4 => 'difficulte_nivo'),
					'sortable-fields' => array(0 => '`lieu_et_scene`.`id_lets`', 1 => 2, 2 => 3, 3 => 4, 4 => 5, 5 => 6, 6 => 7, 7 => 8, 8 => 9, 9 => 10, 10 => '`Dossier_histoire1`.`titre_histoire`', 11 => 12),
					'records-per-page' => 10,
					'default-sort-by' => false,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-lieu_et_scene',
					'template-printable' => 'children-lieu_et_scene-printable',
					'query' => "SELECT `lieu_et_scene`.`id_lets` as 'id_lets', `lieu_et_scene`.`nom_du_lieu` as 'nom_du_lieu', `lieu_et_scene`.`illustration` as 'illustration', `lieu_et_scene`.`description` as 'description', `lieu_et_scene`.`difficulte_nivo` as 'difficulte_nivo', `lieu_et_scene`.`condition_entree` as 'condition_entree', `lieu_et_scene`.`condition_sortie` as 'condition_sortie', IF(    CHAR_LENGTH(`Objets1`.`nom_objet`) || CHAR_LENGTH(`Objets1`.`illustration`), CONCAT_WS('',   `Objets1`.`nom_objet`, `Objets1`.`illustration`), '') as 'objet_present', IF(    CHAR_LENGTH(`personnages1`.`nom`) || CHAR_LENGTH(`personnages1`.`illustration`), CONCAT_WS('',   `personnages1`.`nom`, `personnages1`.`illustration`), '') as 'persos_present', `lieu_et_scene`.`creer_par` as 'creer_par', IF(    CHAR_LENGTH(`Dossier_histoire1`.`titre_histoire`), CONCAT_WS('',   `Dossier_histoire1`.`titre_histoire`), '') as 'rattache_a_dos2j', IF(    CHAR_LENGTH(`sequence1`.`numero_ordre`) || CHAR_LENGTH(`sequence1`.`titre`), CONCAT_WS('',   `sequence1`.`numero_ordre`, ' ', `sequence1`.`titre`), '') as 'rattache_a_seq' FROM `lieu_et_scene` LEFT JOIN `Objets` as Objets1 ON `Objets1`.`id_objet`=`lieu_et_scene`.`objet_present` LEFT JOIN `personnages` as personnages1 ON `personnages1`.`id_perso`=`lieu_et_scene`.`persos_present` LEFT JOIN `Dossier_histoire` as Dossier_histoire1 ON `Dossier_histoire1`.`id2dossier`=`lieu_et_scene`.`rattache_a_dos2j` LEFT JOIN `sequence` as sequence1 ON `sequence1`.`id_sequence`=`lieu_et_scene`.`rattache_a_seq` "
				),
				'rattache_a_seq' => array(   
					'parent-table' => 'sequence',
					'parent-primary-key' => 'id_sequence',
					'child-primary-key' => 'id_lets',
					'child-primary-key-index' => 0,
					'tab-label' => 'Lieu et scene <span class="hidden child-label-lieu_et_scene child-field-caption">(Rattache a seq)</span>',
					'auto-close' => false,
					'table-icon' => 'resources/table_icons/application_view_gallery.png',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => array(1 => 'Nom du lieu', 2 => 'Illustration', 3 => 'Description', 4 => 'Difficulte nivo'),
					'display-field-names' => array(1 => 'nom_du_lieu', 2 => 'illustration', 3 => 'description', 4 => 'difficulte_nivo'),
					'sortable-fields' => array(0 => '`lieu_et_scene`.`id_lets`', 1 => 2, 2 => 3, 3 => 4, 4 => 5, 5 => 6, 6 => 7, 7 => 8, 8 => 9, 9 => 10, 10 => '`Dossier_histoire1`.`titre_histoire`', 11 => 12),
					'records-per-page' => 10,
					'default-sort-by' => false,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-lieu_et_scene',
					'template-printable' => 'children-lieu_et_scene-printable',
					'query' => "SELECT `lieu_et_scene`.`id_lets` as 'id_lets', `lieu_et_scene`.`nom_du_lieu` as 'nom_du_lieu', `lieu_et_scene`.`illustration` as 'illustration', `lieu_et_scene`.`description` as 'description', `lieu_et_scene`.`difficulte_nivo` as 'difficulte_nivo', `lieu_et_scene`.`condition_entree` as 'condition_entree', `lieu_et_scene`.`condition_sortie` as 'condition_sortie', IF(    CHAR_LENGTH(`Objets1`.`nom_objet`) || CHAR_LENGTH(`Objets1`.`illustration`), CONCAT_WS('',   `Objets1`.`nom_objet`, `Objets1`.`illustration`), '') as 'objet_present', IF(    CHAR_LENGTH(`personnages1`.`nom`) || CHAR_LENGTH(`personnages1`.`illustration`), CONCAT_WS('',   `personnages1`.`nom`, `personnages1`.`illustration`), '') as 'persos_present', `lieu_et_scene`.`creer_par` as 'creer_par', IF(    CHAR_LENGTH(`Dossier_histoire1`.`titre_histoire`), CONCAT_WS('',   `Dossier_histoire1`.`titre_histoire`), '') as 'rattache_a_dos2j', IF(    CHAR_LENGTH(`sequence1`.`numero_ordre`) || CHAR_LENGTH(`sequence1`.`titre`), CONCAT_WS('',   `sequence1`.`numero_ordre`, ' ', `sequence1`.`titre`), '') as 'rattache_a_seq' FROM `lieu_et_scene` LEFT JOIN `Objets` as Objets1 ON `Objets1`.`id_objet`=`lieu_et_scene`.`objet_present` LEFT JOIN `personnages` as personnages1 ON `personnages1`.`id_perso`=`lieu_et_scene`.`persos_present` LEFT JOIN `Dossier_histoire` as Dossier_histoire1 ON `Dossier_histoire1`.`id2dossier`=`lieu_et_scene`.`rattache_a_dos2j` LEFT JOIN `sequence` as sequence1 ON `sequence1`.`id_sequence`=`lieu_et_scene`.`rattache_a_seq` "
				)
			),
			'ref_badges' => array(   
			),
			'ref_sequences' => array(   
			),
			'ref_mission' => array(   
			),
			'boiteaid' => array(   
			),
			'ref_capteur' => array(   
			)
		);

	/*************************************/
	/* End of configuration */


	$currDir = dirname(__FILE__);
	include("{$currDir}/defaultLang.php");
	include("{$currDir}/language.php");
	include("{$currDir}/lib.php");
	@header('Content-Type: text/html; charset=' . datalist_db_encoding);

	handle_maintenance();

	/**
	* dynamic configuration based on current user's permissions
	* $userPCConfig array is populated only with parent tables where the user has access to
	* at least one child table
	*/
	$userPCConfig = array();
	foreach($pcConfig as $pcChildTable => $ChildrenLookups){
		$permChild = getTablePermissions($pcChildTable);
		if($permChild[2]){ // user can view records of the child table, so proceed to check children lookups
			foreach($ChildrenLookups as $ChildLookupField => $ChildConfig){
				$permParent = getTablePermissions($ChildConfig['parent-table']);
				if($permParent[2]){ // user can view records of parent table
					$userPCConfig[$pcChildTable][$ChildLookupField] = $pcConfig[$pcChildTable][$ChildLookupField];
					// show add new only if configured above AND the user has insert permission
					if($permChild[1] && $pcConfig[$pcChildTable][$ChildLookupField]['display-add-new']){
						$userPCConfig[$pcChildTable][$ChildLookupField]['display-add-new'] = true;
					}else{
						$userPCConfig[$pcChildTable][$ChildLookupField]['display-add-new'] = false;
					}
				}
			}
		}
	}

	/* Receive, UTF-convert, and validate parameters */
	$ParentTable = $_REQUEST['ParentTable']; // needed only with operation=show-children, will be validated in the processing code
	$ChildTable = $_REQUEST['ChildTable'];
		if(!in_array($ChildTable, array_keys($userPCConfig))){
			/* defaults to first child table in config array if not provided */
			$ChildTable = current(array_keys($userPCConfig));
		}
		if(!$ChildTable){ die('<!-- No tables accessible to current user -->'); }
	$SelectedID = strip_tags($_REQUEST['SelectedID']);
	$ChildLookupField = $_REQUEST['ChildLookupField'];
		if(!in_array($ChildLookupField, array_keys($userPCConfig[$ChildTable]))){
			/* defaults to first lookup in current child config array if not provided */
			$ChildLookupField = current(array_keys($userPCConfig[$ChildTable]));
		}
	$Page = intval($_REQUEST['Page']);
		if($Page < 1){
			$Page = 1;
		}
	$SortBy = ($_REQUEST['SortBy'] != '' ? abs(intval($_REQUEST['SortBy'])) : false);
		if(!in_array($SortBy, array_keys($userPCConfig[$ChildTable][$ChildLookupField]['sortable-fields']), true)){
			$SortBy = $userPCConfig[$ChildTable][$ChildLookupField]['default-sort-by'];
		}
	$SortDirection = strtolower($_REQUEST['SortDirection']);
		if(!in_array($SortDirection, array('asc', 'desc'))){
			$SortDirection = $userPCConfig[$ChildTable][$ChildLookupField]['default-sort-direction'];
		}
	$Operation = strtolower($_REQUEST['Operation']);
		if(!in_array($Operation, array('get-records', 'show-children', 'get-records-printable', 'show-children-printable'))){
			$Operation = 'get-records';
		}

	/* process requested operation */
	switch($Operation){
		/************************************************/
		case 'show-children':
			/* populate HTML and JS content with children tabs */
			$tabLabels = $tabPanels = $tabLoaders = '';
			foreach($userPCConfig as $ChildTable => $childLookups){
				foreach($childLookups as $ChildLookupField => $childConfig){
					if($childConfig['parent-table'] == $ParentTable){
						$TableIcon = ($childConfig['table-icon'] ? "<img src=\"{$childConfig['table-icon']}\" border=\"0\" />" : '');
						$tabLabels .= sprintf('<li%s><a href="#panel_%s-%s" id="tab_%s-%s" data-toggle="tab">%s%s</a></li>' . "\n\t\t\t\t\t",($tabLabels ? '' : ' class="active"'), $ChildTable, $ChildLookupField, $ChildTable, $ChildLookupField, $TableIcon, $childConfig['tab-label']);
						$tabPanels .= sprintf('<div id="panel_%s-%s" class="tab-pane%s"><img src="loading.gif" align="top" />%s</div>' . "\n\t\t\t\t", $ChildTable, $ChildLookupField, ($tabPanels ? '' : ' active'), $Translation['Loading ...']);
						$tabLoaders .= sprintf('post("parent-children.php", { ChildTable: "%s", ChildLookupField: "%s", SelectedID: "%s", Page: 1, SortBy: "", SortDirection: "", Operation: "get-records" }, "panel_%s-%s");' . "\n\t\t\t\t", $ChildTable, $ChildLookupField, addslashes($SelectedID), $ChildTable, $ChildLookupField);
					}
				}
			}

			if(!$tabLabels){ die('<!-- no children of current parent table are accessible to current user -->'); }
			?>
			<div id="children-tabs">
				<ul class="nav nav-tabs">
					<?php echo $tabLabels; ?>
				</ul>
				<span id="pc-loading"></span>
			</div>
			<div class="tab-content"><?php echo $tabPanels; ?></div>

			<script>
				$j(function(){
					/* for iOS, avoid loading child tabs in modals */
					var iOS = /(iPad|iPhone|iPod)/g.test(navigator.userAgent);
					var embedded = ($j('.navbar').length == 0);
					if(iOS && embedded){
						$j('#children-tabs').next('.tab-content').remove();
						$j('#children-tabs').remove();
						return;
					}

					/* ajax loading of each tab's contents */
					<?php echo $tabLoaders; ?>

					/* show child field caption on tab title in case the same child table appears more than once */
					$j('.child-field-caption').each(function() {
						var clss = $j(this).attr('class').split(/\s+/).reduce(function(rc, cc) {
							return (cc.match(/child-label-.*/) ? '.' + cc : rc);
						}, '');

						// if class occurs more than once, remove .hidden
						if($j(clss).length > 1) $j(clss).removeClass('hidden');
					})
				})
			</script>
			<?php
			break;

		/************************************************/
		case 'show-children-printable':
			/* populate HTML and JS content with children buttons */
			$tabLabels = $tabPanels = $tabLoaders = '';
			foreach($userPCConfig as $ChildTable => $childLookups){
				foreach($childLookups as $ChildLookupField => $childConfig){
					if($childConfig['parent-table'] == $ParentTable){
						$TableIcon = ($childConfig['table-icon'] ? "<img src=\"{$childConfig['table-icon']}\" border=\"0\" />" : '');
						$tabLabels .= sprintf('<button type="button" class="btn btn-default" data-target="#panel_%s-%s" id="tab_%s-%s" data-toggle="collapse">%s %s</button>' . "\n\t\t\t\t\t", $ChildTable, $ChildLookupField, $ChildTable, $ChildLookupField, $TableIcon, $childConfig['tab-label']);
						$tabPanels .= sprintf('<div id="panel_%s-%s" class="collapse"><img src="loading.gif" align="top" />%s</div>' . "\n\t\t\t\t", $ChildTable, $ChildLookupField, $Translation['Loading ...']);
						$tabLoaders .= sprintf('post("parent-children.php", { ChildTable: "%s", ChildLookupField: "%s", SelectedID: "%s", Page: 1, SortBy: "", SortDirection: "", Operation: "get-records-printable" }, "panel_%s-%s");' . "\n\t\t\t\t", $ChildTable, $ChildLookupField, addslashes($SelectedID), $ChildTable, $ChildLookupField);
					}
				}
			}

			if(!$tabLabels){ die('<!-- no children of current parent table are accessible to current user -->'); }
			?>
			<div id="children-tabs" class="hidden-print">
				<div class="btn-group btn-group-lg">
					<?php echo $tabLabels; ?>
				</div>
				<span id="pc-loading"></span>
			</div>
			<div class="vspacer-lg"><?php echo $tabPanels; ?></div>

			<script>
				$j(function(){
					/* for iOS, avoid loading child tabs in modals */
					var iOS = /(iPad|iPhone|iPod)/g.test(navigator.userAgent);
					var embedded = ($j('.navbar').length == 0);
					if(iOS && embedded){
						$j('#children-tabs').next('.tab-content').remove();
						$j('#children-tabs').remove();
						return;
					}

					/* ajax loading of each tab's contents */
					<?php echo $tabLoaders; ?>
				})
			</script>
			<?php
			break;

		/************************************************/
		case 'get-records-printable':
		default: /* default is 'get-records' */

			if($Operation == 'get-records-printable'){
				$userPCConfig[$ChildTable][$ChildLookupField]['records-per-page'] = 2000;
			}

			// build the user permissions limiter
			$permissionsWhere = $permissionsJoin = '';
			$permChild = getTablePermissions($ChildTable);
			if($permChild[2] == 1){ // user can view only his own records
				$permissionsWhere = "`$ChildTable`.`{$userPCConfig[$ChildTable][$ChildLookupField]['child-primary-key']}`=`membership_userrecords`.`pkValue` AND `membership_userrecords`.`tableName`='$ChildTable' AND LCASE(`membership_userrecords`.`memberID`)='".getLoggedMemberID()."'";
			}elseif($permChild[2] == 2){ // user can view only his group's records
				$permissionsWhere = "`$ChildTable`.`{$userPCConfig[$ChildTable][$ChildLookupField]['child-primary-key']}`=`membership_userrecords`.`pkValue` AND `membership_userrecords`.`tableName`='$ChildTable' AND `membership_userrecords`.`groupID`='".getLoggedGroupID()."'";
			}elseif($permChild[2] == 3){ // user can view all records
				/* that's the only case remaining ... no need to modify the query in this case */
			}
			$permissionsJoin = ($permissionsWhere ? ", `membership_userrecords`" : '');

			// build the count query
			$forcedWhere = $userPCConfig[$ChildTable][$ChildLookupField]['forced-where'];
			$query = 
				preg_replace('/^select .* from /i', 'SELECT count(1) FROM ', $userPCConfig[$ChildTable][$ChildLookupField]['query']) .
				$permissionsJoin . " WHERE " .
				($permissionsWhere ? "( $permissionsWhere )" : "( 1=1 )") . " AND " .
				($forcedWhere ? "( $forcedWhere )" : "( 2=2 )") . " AND " .
				"`$ChildTable`.`$ChildLookupField`='" . makeSafe($SelectedID) . "'";
			$totalMatches = sqlValue($query);

			// make sure $Page is <= max pages
			$maxPage = ceil($totalMatches / $userPCConfig[$ChildTable][$ChildLookupField]['records-per-page']);
			if($Page > $maxPage){ $Page = $maxPage; }

			// initiate output data array
			$data = array(
				'config' => $userPCConfig[$ChildTable][$ChildLookupField],
				'parameters' => array(
					'ChildTable' => $ChildTable,
					'ChildLookupField' => $ChildLookupField,
					'SelectedID' => $SelectedID,
					'Page' => $Page,
					'SortBy' => $SortBy,
					'SortDirection' => $SortDirection,
					'Operation' => $Operation
				),
				'records' => array(),
				'totalMatches' => $totalMatches
			);

			// build the data query
			if($totalMatches){ // if we have at least one record, proceed with fetching data
				$startRecord = $userPCConfig[$ChildTable][$ChildLookupField]['records-per-page'] * ($Page - 1);
				$data['query'] = 
					$userPCConfig[$ChildTable][$ChildLookupField]['query'] .
					$permissionsJoin . " WHERE " .
					($permissionsWhere ? "( $permissionsWhere )" : "( 1=1 )") . " AND " .
					($forcedWhere ? "( $forcedWhere )" : "( 2=2 )") . " AND " .
					"`$ChildTable`.`$ChildLookupField`='" . makeSafe($SelectedID) . "'" . 
					($SortBy !== false && $userPCConfig[$ChildTable][$ChildLookupField]['sortable-fields'][$SortBy] ? " ORDER BY {$userPCConfig[$ChildTable][$ChildLookupField]['sortable-fields'][$SortBy]} $SortDirection" : '') .
					" LIMIT $startRecord, {$userPCConfig[$ChildTable][$ChildLookupField]['records-per-page']}";
				$res = sql($data['query'], $eo);
				while($row = db_fetch_row($res)){
					$data['records'][$row[$userPCConfig[$ChildTable][$ChildLookupField]['child-primary-key-index']]] = $row;
				}
			}else{ // if no matching records
				$startRecord = 0;
			}

			if($Operation == 'get-records-printable'){
				$response = loadView($userPCConfig[$ChildTable][$ChildLookupField]['template-printable'], $data);
			}else{
				$response = loadView($userPCConfig[$ChildTable][$ChildLookupField]['template'], $data);
			}

			// change name space to ensure uniqueness
			$uniqueNameSpace = $ChildTable.ucfirst($ChildLookupField).'GetRecords';
			echo str_replace("{$ChildTable}GetChildrenRecordsList", $uniqueNameSpace, $response);
		/************************************************/
	}
