<?php

// Data functions (insert, update, delete, form) for table redacteur

// This script and data application were generated by AppGini 5.75
// Download AppGini for free from https://bigprof.com/appgini/download/

function redacteur_insert(){
	global $Translation;

	// mm: can member insert record?
	$arrPerm=getTablePermissions('redacteur');
	if(!$arrPerm[1]){
		return false;
	}

	$data['member_id'] = parseCode('<%%creatorUsername%%>', true);
	$data['prenom'] = makeSafe($_REQUEST['prenom']);
		if($data['prenom'] == empty_lookup_value){ $data['prenom'] = ''; }
	$data['nom'] = makeSafe($_REQUEST['nom']);
		if($data['nom'] == empty_lookup_value){ $data['nom'] = ''; }
	$data['email'] = makeSafe($_REQUEST['email']);
		if($data['email'] == empty_lookup_value){ $data['email'] = ''; }
	$data['score_total'] = makeSafe($_REQUEST['score_total']);
		if($data['score_total'] == empty_lookup_value){ $data['score_total'] = ''; }
	$data['badges'] = makeSafe($_REQUEST['badges']);
		if($data['badges'] == empty_lookup_value){ $data['badges'] = ''; }
	$data['score_hist'] = makeSafe($_REQUEST['score_hist']);
		if($data['score_hist'] == empty_lookup_value){ $data['score_hist'] = ''; }
	$data['score_obj'] = makeSafe($_REQUEST['score_obj']);
		if($data['score_obj'] == empty_lookup_value){ $data['score_obj'] = ''; }
	$data['score_moy'] = makeSafe($_REQUEST['score_moy']);
		if($data['score_moy'] == empty_lookup_value){ $data['score_moy'] = ''; }
	$data['score_objets'] = makeSafe($_REQUEST['score_objets']);
		if($data['score_objets'] == empty_lookup_value){ $data['score_objets'] = ''; }
	$data['score_perso'] = makeSafe($_REQUEST['score_perso']);
		if($data['score_perso'] == empty_lookup_value){ $data['score_perso'] = ''; }
	$data['score_lets'] = makeSafe($_REQUEST['score_lets']);
		if($data['score_lets'] == empty_lookup_value){ $data['score_lets'] = ''; }
	if($data['score_total'] == '') $data['score_total'] = "0";
	if($data['score_hist'] == '') $data['score_hist'] = "0";
	if($data['score_obj'] == '') $data['score_obj'] = "0";
	if($data['score_moy'] == '') $data['score_moy'] = "0";
	if($data['score_objets'] == '') $data['score_objets'] = "0";
	if($data['score_perso'] == '') $data['score_perso'] = "0";
	if($data['score_lets'] == '') $data['score_lets'] = "0";

	// hook: redacteur_before_insert
	if(function_exists('redacteur_before_insert')){
		$args=array();
		if(!redacteur_before_insert($data, getMemberInfo(), $args)){ return false; }
	}

	$o = array('silentErrors' => true);
	sql('insert into `redacteur` set       `member_id`=' . "'{$data['member_id']}'" . ', `prenom`=' . (($data['prenom'] !== '' && $data['prenom'] !== NULL) ? "'{$data['prenom']}'" : 'NULL') . ', `nom`=' . (($data['nom'] !== '' && $data['nom'] !== NULL) ? "'{$data['nom']}'" : 'NULL') . ', `email`=' . (($data['email'] !== '' && $data['email'] !== NULL) ? "'{$data['email']}'" : 'NULL') . ', `score_total`=' . (($data['score_total'] !== '' && $data['score_total'] !== NULL) ? "'{$data['score_total']}'" : 'NULL') . ', `badges`=' . (($data['badges'] !== '' && $data['badges'] !== NULL) ? "'{$data['badges']}'" : 'NULL'), $o);
	if($o['error']!=''){
		echo $o['error'];
		echo "<a href=\"redacteur_view.php?addNew_x=1\">{$Translation['< back']}</a>";
		exit;
	}

	$recID = db_insert_id(db_link());

	// hook: redacteur_after_insert
	if(function_exists('redacteur_after_insert')){
		$res = sql("select * from `redacteur` where `id_redact`='" . makeSafe($recID, false) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=array();
		if(!redacteur_after_insert($data, getMemberInfo(), $args)){ return $recID; }
	}

	// mm: save ownership data
	set_record_owner('redacteur', $recID, getLoggedMemberID());

	return $recID;
}

function redacteur_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false){
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('redacteur');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='redacteur' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='redacteur' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: redacteur_before_delete
	if(function_exists('redacteur_before_delete')){
		$args=array();
		if(!redacteur_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	// child table: Dossier_histoire
	$res = sql("select `id_redact` from `redacteur` where `id_redact`='$selected_id'", $eo);
	$id_redact = db_fetch_row($res);
	$rires = sql("select count(1) from `Dossier_histoire` where `auteur`='".addslashes($id_redact[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "Dossier_histoire", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "Dossier_histoire", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='redacteur_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='redacteur_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	sql("delete from `redacteur` where `id_redact`='$selected_id'", $eo);

	// hook: redacteur_after_delete
	if(function_exists('redacteur_after_delete')){
		$args=array();
		redacteur_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='redacteur' and pkValue='$selected_id'", $eo);
}

function redacteur_update($selected_id){
	global $Translation;

	// mm: can member edit record?
	$arrPerm=getTablePermissions('redacteur');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='redacteur' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='redacteur' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['prenom'] = makeSafe($_REQUEST['prenom']);
		if($data['prenom'] == empty_lookup_value){ $data['prenom'] = ''; }
	$data['nom'] = makeSafe($_REQUEST['nom']);
		if($data['nom'] == empty_lookup_value){ $data['nom'] = ''; }
	$data['email'] = makeSafe($_REQUEST['email']);
		if($data['email'] == empty_lookup_value){ $data['email'] = ''; }
	$data['score_total'] = makeSafe($_REQUEST['score_total']);
		if($data['score_total'] == empty_lookup_value){ $data['score_total'] = ''; }
	$data['badges'] = makeSafe($_REQUEST['badges']);
		if($data['badges'] == empty_lookup_value){ $data['badges'] = ''; }
	$data['score_hist'] = makeSafe($_REQUEST['score_hist']);
		if($data['score_hist'] == empty_lookup_value){ $data['score_hist'] = ''; }
	$data['score_obj'] = makeSafe($_REQUEST['score_obj']);
		if($data['score_obj'] == empty_lookup_value){ $data['score_obj'] = ''; }
	$data['score_moy'] = makeSafe($_REQUEST['score_moy']);
		if($data['score_moy'] == empty_lookup_value){ $data['score_moy'] = ''; }
	$data['score_objets'] = makeSafe($_REQUEST['score_objets']);
		if($data['score_objets'] == empty_lookup_value){ $data['score_objets'] = ''; }
	$data['score_perso'] = makeSafe($_REQUEST['score_perso']);
		if($data['score_perso'] == empty_lookup_value){ $data['score_perso'] = ''; }
	$data['score_lets'] = makeSafe($_REQUEST['score_lets']);
		if($data['score_lets'] == empty_lookup_value){ $data['score_lets'] = ''; }
	$data['selectedID']=makeSafe($selected_id);

	// hook: redacteur_before_update
	if(function_exists('redacteur_before_update')){
		$args=array();
		if(!redacteur_before_update($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('update `redacteur` set       `prenom`=' . (($data['prenom'] !== '' && $data['prenom'] !== NULL) ? "'{$data['prenom']}'" : 'NULL') . ', `nom`=' . (($data['nom'] !== '' && $data['nom'] !== NULL) ? "'{$data['nom']}'" : 'NULL') . ', `email`=' . (($data['email'] !== '' && $data['email'] !== NULL) ? "'{$data['email']}'" : 'NULL') . ', `score_total`=' . (($data['score_total'] !== '' && $data['score_total'] !== NULL) ? "'{$data['score_total']}'" : 'NULL') . ', `badges`=' . (($data['badges'] !== '' && $data['badges'] !== NULL) ? "'{$data['badges']}'" : 'NULL') . " where `id_redact`='".makeSafe($selected_id)."'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo '<a href="redacteur_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: redacteur_after_update
	if(function_exists('redacteur_after_update')){
		$res = sql("SELECT * FROM `redacteur` WHERE `id_redact`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['id_redact'];
		$args = array();
		if(!redacteur_after_update($data, getMemberInfo(), $args)){ return; }
	}

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."' where tableName='redacteur' and pkValue='".makeSafe($selected_id)."'", $eo);

}

function redacteur_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0, $TemplateDV = '', $TemplateDVP = ''){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('redacteur');
	if(!$arrPerm[1] && $selected_id==''){ return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != ''){
		$dvprint = true;
	}

	$filterer_badges = thisOr(undo_magic_quotes($_REQUEST['filterer_badges']), '');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: badges
	$combo_badges = new DataCombo;

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='redacteur' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='redacteur' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("select * from `redacteur` where `id_redact`='".makeSafe($selected_id)."'", $eo);
		if(!($row = db_fetch_array($res))){
			return error_message($Translation['No records found'], 'redacteur_view.php', false);
		}
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
		$combo_badges->SelectedData = $row['badges'];
	}else{
		$combo_badges->SelectedData = $filterer_badges;
	}
	$combo_badges->HTML = '<span id="badges-container' . $rnd1 . '"></span><input type="hidden" name="badges" id="badges' . $rnd1 . '" value="' . html_attr($combo_badges->SelectedData) . '">';
	$combo_badges->MatchText = '<span id="badges-container-readonly' . $rnd1 . '"></span><input type="hidden" name="badges" id="badges' . $rnd1 . '" value="' . html_attr($combo_badges->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_badges__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['badges'] : $filterer_badges); ?>"};

		jQuery(function() {
			setTimeout(function(){
				if(typeof(badges_reload__RAND__) == 'function') badges_reload__RAND__();
			}, 10); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function badges_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			$j("#badges-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_badges__RAND__.value, t: 'redacteur', f: 'badges' },
						success: function(resp){
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="badges"]').val(resp.results[0].id);
							$j('[id=badges-container-readonly__RAND__]').html('<span id="badges-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=ref_badges_view_parent]').hide(); }else{ $j('.btn[id=ref_badges_view_parent]').show(); }


							if(typeof(badges_update_autofills__RAND__) == 'function') badges_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term){ /* */ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ /* */ return { s: term, p: page, t: 'redacteur', f: 'badges' }; },
					results: function(resp, page){ /* */ return resp; }
				},
				escapeMarkup: function(str){ /* */ return str; }
			}).on('change', function(e){
				AppGini.current_badges__RAND__.value = e.added.id;
				AppGini.current_badges__RAND__.text = e.added.text;
				$j('[name="badges"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=ref_badges_view_parent]').hide(); }else{ $j('.btn[id=ref_badges_view_parent]').show(); }


				if(typeof(badges_update_autofills__RAND__) == 'function') badges_update_autofills__RAND__();
			});

			if(!$j("#badges-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_badges__RAND__.value, t: 'redacteur', f: 'badges' },
					success: function(resp){
						$j('[name="badges"]').val(resp.results[0].id);
						$j('[id=badges-container-readonly__RAND__]').html('<span id="badges-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=ref_badges_view_parent]').hide(); }else{ $j('.btn[id=ref_badges_view_parent]').show(); }

						if(typeof(badges_update_autofills__RAND__) == 'function') badges_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_badges__RAND__.value, t: 'redacteur', f: 'badges' },
				success: function(resp){
					$j('[id=badges-container__RAND__], [id=badges-container-readonly__RAND__]').html('<span id="badges-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=ref_badges_view_parent]').hide(); }else{ $j('.btn[id=ref_badges_view_parent]').show(); }

					if(typeof(badges_update_autofills__RAND__) == 'function') badges_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	if($dvprint){
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/redacteur_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	}else{
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/redacteur_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Auteur details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($arrPerm[1] && !$selected_id){ // allow insert and no record selected?
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return redacteur_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return redacteur_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']){
		$backAction = 'AppGini.closeParentModal(); return false;';
	}else{
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id){
		if(!$_REQUEST['Embedded']) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate){
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return redacteur_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate) || (!$selected_id && !$AllowInsert)){
		$jsReadOnly .= "\tjQuery('#prenom').replaceWith('<div class=\"form-control-static\" id=\"prenom\">' + (jQuery('#prenom').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#nom').replaceWith('<div class=\"form-control-static\" id=\"nom\">' + (jQuery('#nom').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#email').replaceWith('<div class=\"form-control-static\" id=\"email\">' + (jQuery('#email').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#email, #email-edit-link').hide();\n";
		$jsReadOnly .= "\tjQuery('#score_total').replaceWith('<div class=\"form-control-static\" id=\"score_total\">' + (jQuery('#score_total').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#badges').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#badges_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	}elseif(($AllowInsert && !$selected_id) || ($AllowUpdate && $selected_id)){
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(badges)%%>', $combo_badges->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(badges)%%>', $combo_badges->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(badges)%%>', urlencode($combo_badges->MatchText), $templateCode);

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array(  'badges' => array('ref_badges', 'Badges'));
	foreach($lookup_fields as $luf => $ptfc){
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']){
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] && !$_REQUEST['Embedded']){
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id_redact)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(member_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(prenom)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(nom)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(email)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(score_total)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(badges)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(score_hist)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(score_obj)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(score_moy)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(score_objets)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(score_perso)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(score_lets)%%>', '', $templateCode);

	// process values
	if($selected_id){
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id_redact)%%>', safe_html($urow['id_redact']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id_redact)%%>', html_attr($row['id_redact']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id_redact)%%>', urlencode($urow['id_redact']), $templateCode);
		$templateCode = str_replace('<%%VALUE(member_id)%%>', safe_html($urow['member_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(member_id)%%>', urlencode($urow['member_id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(prenom)%%>', safe_html($urow['prenom']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(prenom)%%>', html_attr($row['prenom']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(prenom)%%>', urlencode($urow['prenom']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(nom)%%>', safe_html($urow['nom']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(nom)%%>', html_attr($row['nom']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(nom)%%>', urlencode($urow['nom']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(email)%%>', safe_html($urow['email']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(email)%%>', html_attr($row['email']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(email)%%>', urlencode($urow['email']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(score_total)%%>', safe_html($urow['score_total']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(score_total)%%>', html_attr($row['score_total']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(score_total)%%>', urlencode($urow['score_total']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(badges)%%>', safe_html($urow['badges']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(badges)%%>', html_attr($row['badges']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(badges)%%>', urlencode($urow['badges']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(score_hist)%%>', safe_html($urow['score_hist']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(score_hist)%%>', html_attr($row['score_hist']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(score_hist)%%>', urlencode($urow['score_hist']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(score_obj)%%>', safe_html($urow['score_obj']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(score_obj)%%>', html_attr($row['score_obj']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(score_obj)%%>', urlencode($urow['score_obj']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(score_moy)%%>', safe_html($urow['score_moy']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(score_moy)%%>', html_attr($row['score_moy']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(score_moy)%%>', urlencode($urow['score_moy']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(score_objets)%%>', safe_html($urow['score_objets']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(score_objets)%%>', html_attr($row['score_objets']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(score_objets)%%>', urlencode($urow['score_objets']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(score_perso)%%>', safe_html($urow['score_perso']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(score_perso)%%>', html_attr($row['score_perso']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(score_perso)%%>', urlencode($urow['score_perso']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(score_lets)%%>', safe_html($urow['score_lets']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(score_lets)%%>', html_attr($row['score_lets']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(score_lets)%%>', urlencode($urow['score_lets']), $templateCode);
	}else{
		$templateCode = str_replace('<%%VALUE(id_redact)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id_redact)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(member_id)%%>', '<%%creatorUsername%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(member_id)%%>', urlencode('<%%creatorUsername%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(prenom)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(prenom)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(nom)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(nom)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(email)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(email)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(score_total)%%>', '0', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(score_total)%%>', urlencode('0'), $templateCode);
		$templateCode = str_replace('<%%VALUE(badges)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(badges)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(score_hist)%%>', '0', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(score_hist)%%>', urlencode('0'), $templateCode);
		$templateCode = str_replace('<%%VALUE(score_obj)%%>', '0', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(score_obj)%%>', urlencode('0'), $templateCode);
		$templateCode = str_replace('<%%VALUE(score_moy)%%>', '0', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(score_moy)%%>', urlencode('0'), $templateCode);
		$templateCode = str_replace('<%%VALUE(score_objets)%%>', '0', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(score_objets)%%>', urlencode('0'), $templateCode);
		$templateCode = str_replace('<%%VALUE(score_perso)%%>', '0', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(score_perso)%%>', urlencode('0'), $templateCode);
		$templateCode = str_replace('<%%VALUE(score_lets)%%>', '0', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(score_lets)%%>', urlencode('0'), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode = str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == ''){
		$templateCode .= "\n\n<script>\$j(function(){\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption){
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id){
			$templateCode.="\n\tif(document.getElementById('emailEdit')){ document.getElementById('emailEdit').style.display='inline'; }";
			$templateCode.="\n\tif(document.getElementById('emailEditLink')){ document.getElementById('emailEditLink').style.display='none'; }";
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('redacteur');
	if($selected_id){
		$jdata = get_joined_record('redacteur', $selected_id);
		if($jdata === false) $jdata = get_defaults('redacteur');
		$rdata = $row;
	}
	$templateCode .= loadView('redacteur-ajax-cache', array('rdata' => $rdata, 'jdata' => $jdata));

	// hook: redacteur_dv
	if(function_exists('redacteur_dv')){
		$args=array();
		redacteur_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>