<?php
// This script and data application were generated by AppGini 5.75
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/ref_badges.php");
	include("$currDir/ref_badges_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('ref_badges');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "ref_badges";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(   
		"`ref_badges`.`id_badge`" => "id_badge",
		"`ref_badges`.`titre`" => "titre",
		"`ref_badges`.`description`" => "description",
		"`ref_badges`.`domaine`" => "domaine",
		"`ref_badges`.`score_min`" => "score_min",
		"`ref_badges`.`score_max`" => "score_max",
		"`ref_badges`.`icone_badge`" => "icone_badge"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`ref_badges`.`id_badge`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => '`ref_badges`.`score_min`',
		6 => 6,
		7 => 7
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(   
		"`ref_badges`.`id_badge`" => "id_badge",
		"`ref_badges`.`titre`" => "titre",
		"`ref_badges`.`description`" => "description",
		"`ref_badges`.`domaine`" => "domaine",
		"`ref_badges`.`score_min`" => "score_min",
		"`ref_badges`.`score_max`" => "score_max",
		"`ref_badges`.`icone_badge`" => "icone_badge"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(   
		"`ref_badges`.`id_badge`" => "Id badge",
		"`ref_badges`.`titre`" => "Titre",
		"`ref_badges`.`description`" => "Description",
		"`ref_badges`.`domaine`" => "Domaine",
		"`ref_badges`.`score_min`" => "Score min",
		"`ref_badges`.`score_max`" => "Score max",
		"`ref_badges`.`icone_badge`" => "Icone badge"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(   
		"`ref_badges`.`id_badge`" => "id_badge",
		"`ref_badges`.`titre`" => "titre",
		"`ref_badges`.`description`" => "description",
		"`ref_badges`.`domaine`" => "domaine",
		"`ref_badges`.`score_min`" => "score_min",
		"`ref_badges`.`score_max`" => "score_max",
		"`ref_badges`.`icone_badge`" => "icone_badge"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array();

	$x->QueryFrom = "`ref_badges` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "ref_badges_view.php";
	$x->RedirectAfterInsert = "ref_badges_view.php?SelectedID=#ID#";
	$x->TableTitle = "Badges ref";
	$x->TableIcon = "table.gif";
	$x->PrimaryKey = "`ref_badges`.`id_badge`";

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("Titre", "Description", "Domaine", "Score min", "Score max", "Icone badge");
	$x->ColFieldName = array('titre', 'description', 'domaine', 'score_min', 'score_max', 'icone_badge');
	$x->ColNumber  = array(2, 3, 4, 5, 6, 7);

	// template paths below are based on the app main directory
	$x->Template = 'templates/ref_badges_templateTV.html';
	$x->SelectedTemplate = 'templates/ref_badges_templateTVS.html';
	$x->TemplateDV = 'templates/ref_badges_templateDV.html';
	$x->TemplateDVP = 'templates/ref_badges_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `ref_badges`.`id_badge`=membership_userrecords.pkValue and membership_userrecords.tableName='ref_badges' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `ref_badges`.`id_badge`=membership_userrecords.pkValue and membership_userrecords.tableName='ref_badges' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`ref_badges`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: ref_badges_init
	$render=TRUE;
	if(function_exists('ref_badges_init')){
		$args=array();
		$render=ref_badges_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: ref_badges_header
	$headerCode='';
	if(function_exists('ref_badges_header')){
		$args=array();
		$headerCode=ref_badges_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: ref_badges_footer
	$footerCode='';
	if(function_exists('ref_badges_footer')){
		$args=array();
		$footerCode=ref_badges_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>