<?php

// Data functions (insert, update, delete, form) for table sequence

// This script and data application were generated by AppGini 5.61
// Download AppGini for free from https://bigprof.com/appgini/download/

function sequence_insert(){
	global $Translation;

	// mm: can member insert record?
	$arrPerm=getTablePermissions('sequence');
	if(!$arrPerm[1]){
		return false;
	}

	$data['numero_ordre'] = makeSafe($_REQUEST['numero_ordre']);
		if($data['numero_ordre'] == empty_lookup_value){ $data['numero_ordre'] = ''; }
	$data['titre'] = makeSafe($_REQUEST['titre']);
		if($data['titre'] == empty_lookup_value){ $data['titre'] = ''; }
	$data['rattache_a_chapitre'] = makeSafe($_REQUEST['rattache_a_chapitre']);
		if($data['rattache_a_chapitre'] == empty_lookup_value){ $data['rattache_a_chapitre'] = ''; }
	$data['difficulte'] = makeSafe($_REQUEST['difficulte']);
		if($data['difficulte'] == empty_lookup_value){ $data['difficulte'] = ''; }
	$data['description'] = makeSafe($_REQUEST['description']);
		if($data['description'] == empty_lookup_value){ $data['description'] = ''; }
	$data['auteur'] = parseCode('<%%creatorUsername%%>', true);
	$data['modele'] = makeSafe($_REQUEST['modele']);
		if($data['modele'] == empty_lookup_value){ $data['modele'] = ''; }
	if($data['numero_ordre']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Numero de la s&#233;quence': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['titre']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Titre': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}

	// hook: sequence_before_insert
	if(function_exists('sequence_before_insert')){
		$args=array();
		if(!sequence_before_insert($data, getMemberInfo(), $args)){ return false; }
	}

	$o = array('silentErrors' => true);
	sql('insert into `sequence` set       `numero_ordre`=' . (($data['numero_ordre'] !== '' && $data['numero_ordre'] !== NULL) ? "'{$data['numero_ordre']}'" : 'NULL') . ', `titre`=' . (($data['titre'] !== '' && $data['titre'] !== NULL) ? "'{$data['titre']}'" : 'NULL') . ', `difficulte`=' . (($data['difficulte'] !== '' && $data['difficulte'] !== NULL) ? "'{$data['difficulte']}'" : 'NULL') . ', `description`=' . (($data['description'] !== '' && $data['description'] !== NULL) ? "'{$data['description']}'" : 'NULL') . ', `auteur`=' . "'{$data['auteur']}'" . ', `modele`=' . (($data['modele'] !== '' && $data['modele'] !== NULL) ? "'{$data['modele']}'" : 'NULL'), $o);
	if($o['error']!=''){
		echo $o['error'];
		echo "<a href=\"sequence_view.php?addNew_x=1\">{$Translation['< back']}</a>";
		exit;
	}

	$recID = db_insert_id(db_link());

	// automatic rattache_a_chapitre
	if($_REQUEST['filterer_rattache_a_chapitre']){
		sql("update `sequence` set `rattache_a_chapitre`='" . makeSafe($_REQUEST['filterer_rattache_a_chapitre']) . "' where `id_sequence`='" . makeSafe($recID, false) . "'", $eo);
	}

	// hook: sequence_after_insert
	if(function_exists('sequence_after_insert')){
		$res = sql("select * from `sequence` where `id_sequence`='" . makeSafe($recID, false) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=array();
		if(!sequence_after_insert($data, getMemberInfo(), $args)){ return $recID; }
	}

	// mm: save ownership data
	sql("insert ignore into membership_userrecords set tableName='sequence', pkValue='" . makeSafe($recID, false) . "', memberID='" . makeSafe(getLoggedMemberID(), false) . "', dateAdded='" . time() . "', dateUpdated='" . time() . "', groupID='" . getLoggedGroupID() . "'", $eo);

	return $recID;
}

function sequence_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false){
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('sequence');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='sequence' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='sequence' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: sequence_before_delete
	if(function_exists('sequence_before_delete')){
		$args=array();
		if(!sequence_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	// child table: Objets
	$res = sql("select `id_sequence` from `sequence` where `id_sequence`='$selected_id'", $eo);
	$id_sequence = db_fetch_row($res);
	$rires = sql("select count(1) from `Objets` where `rattache_a_seq`='".addslashes($id_sequence[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "Objets", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "Objets", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='sequence_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='sequence_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	// child table: personnages
	$res = sql("select `id_sequence` from `sequence` where `id_sequence`='$selected_id'", $eo);
	$id_sequence = db_fetch_row($res);
	$rires = sql("select count(1) from `personnages` where `rattache_a_seq`='".addslashes($id_sequence[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "personnages", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "personnages", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='sequence_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='sequence_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	// child table: lieu_et_scene
	$res = sql("select `id_sequence` from `sequence` where `id_sequence`='$selected_id'", $eo);
	$id_sequence = db_fetch_row($res);
	$rires = sql("select count(1) from `lieu_et_scene` where `rattache_a_seq`='".addslashes($id_sequence[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "lieu_et_scene", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "lieu_et_scene", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='sequence_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='sequence_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	sql("delete from `sequence` where `id_sequence`='$selected_id'", $eo);

	// hook: sequence_after_delete
	if(function_exists('sequence_after_delete')){
		$args=array();
		sequence_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='sequence' and pkValue='$selected_id'", $eo);
}

function sequence_update($selected_id){
	global $Translation;

	// mm: can member edit record?
	$arrPerm=getTablePermissions('sequence');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='sequence' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='sequence' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['numero_ordre'] = makeSafe($_REQUEST['numero_ordre']);
		if($data['numero_ordre'] == empty_lookup_value){ $data['numero_ordre'] = ''; }
	if($data['numero_ordre']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Numero de la s&#233;quence': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['titre'] = makeSafe($_REQUEST['titre']);
		if($data['titre'] == empty_lookup_value){ $data['titre'] = ''; }
	if($data['titre']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Titre': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['rattache_a_chapitre'] = makeSafe($_REQUEST['rattache_a_chapitre']);
		if($data['rattache_a_chapitre'] == empty_lookup_value){ $data['rattache_a_chapitre'] = ''; }
	$data['difficulte'] = makeSafe($_REQUEST['difficulte']);
		if($data['difficulte'] == empty_lookup_value){ $data['difficulte'] = ''; }
	$data['description'] = makeSafe($_REQUEST['description']);
		if($data['description'] == empty_lookup_value){ $data['description'] = ''; }
	$data['modele'] = makeSafe($_REQUEST['modele']);
		if($data['modele'] == empty_lookup_value){ $data['modele'] = ''; }
	$data['selectedID']=makeSafe($selected_id);

	// hook: sequence_before_update
	if(function_exists('sequence_before_update')){
		$args=array();
		if(!sequence_before_update($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('update `sequence` set       `numero_ordre`=' . (($data['numero_ordre'] !== '' && $data['numero_ordre'] !== NULL) ? "'{$data['numero_ordre']}'" : 'NULL') . ', `titre`=' . (($data['titre'] !== '' && $data['titre'] !== NULL) ? "'{$data['titre']}'" : 'NULL') . ', `difficulte`=' . (($data['difficulte'] !== '' && $data['difficulte'] !== NULL) ? "'{$data['difficulte']}'" : 'NULL') . ', `description`=' . (($data['description'] !== '' && $data['description'] !== NULL) ? "'{$data['description']}'" : 'NULL') . ', `modele`=' . (($data['modele'] !== '' && $data['modele'] !== NULL) ? "'{$data['modele']}'" : 'NULL') . " where `id_sequence`='".makeSafe($selected_id)."'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo '<a href="sequence_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: sequence_after_update
	if(function_exists('sequence_after_update')){
		$res = sql("SELECT * FROM `sequence` WHERE `id_sequence`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['id_sequence'];
		$args = array();
		if(!sequence_after_update($data, getMemberInfo(), $args)){ return; }
	}

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."' where tableName='sequence' and pkValue='".makeSafe($selected_id)."'", $eo);

}

function sequence_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0, $TemplateDV = '', $TemplateDVP = ''){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('sequence');
	if(!$arrPerm[1] && $selected_id==''){ return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != ''){
		$dvprint = true;
	}

	$filterer_rattache_a_chapitre = thisOr(undo_magic_quotes($_REQUEST['filterer_rattache_a_chapitre']), '');
	$filterer_modele = thisOr(undo_magic_quotes($_REQUEST['filterer_modele']), '');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: rattache_a_chapitre
	$combo_rattache_a_chapitre = new DataCombo;
	// combobox: difficulte
	$combo_difficulte = new Combo;
	$combo_difficulte->ListType = 0;
	$combo_difficulte->MultipleSeparator = ', ';
	$combo_difficulte->ListBoxHeight = 10;
	$combo_difficulte->RadiosPerLine = 1;
	if(is_file(dirname(__FILE__).'/hooks/sequence.difficulte.csv')){
		$difficulte_data = addslashes(implode('', @file(dirname(__FILE__).'/hooks/sequence.difficulte.csv')));
		$combo_difficulte->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions($difficulte_data)));
		$combo_difficulte->ListData = $combo_difficulte->ListItem;
	}else{
		$combo_difficulte->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions("introduction;;demo;;facile;;moyen;;difficile;;boss2fin")));
		$combo_difficulte->ListData = $combo_difficulte->ListItem;
	}
	$combo_difficulte->SelectName = 'difficulte';
	// combobox: modele
	$combo_modele = new DataCombo;

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='sequence' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='sequence' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("select * from `sequence` where `id_sequence`='".makeSafe($selected_id)."'", $eo);
		if(!($row = db_fetch_array($res))){
			return error_message($Translation['No records found'], 'sequence_view.php', false);
		}
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
		$combo_rattache_a_chapitre->SelectedData = $row['rattache_a_chapitre'];
		$combo_difficulte->SelectedData = $row['difficulte'];
		$combo_modele->SelectedData = $row['modele'];
	}else{
		$combo_rattache_a_chapitre->SelectedData = $filterer_rattache_a_chapitre;
		$combo_difficulte->SelectedText = ( $_REQUEST['FilterField'][1]=='5' && $_REQUEST['FilterOperator'][1]=='<=>' ? (get_magic_quotes_gpc() ? stripslashes($_REQUEST['FilterValue'][1]) : $_REQUEST['FilterValue'][1]) : "");
		$combo_modele->SelectedData = $filterer_modele;
	}
	$combo_rattache_a_chapitre->HTML = '<span id="rattache_a_chapitre-container' . $rnd1 . '"></span><input type="hidden" name="rattache_a_chapitre" id="rattache_a_chapitre' . $rnd1 . '" value="' . html_attr($combo_rattache_a_chapitre->SelectedData) . '">';
	$combo_rattache_a_chapitre->MatchText = '<span id="rattache_a_chapitre-container-readonly' . $rnd1 . '"></span><input type="hidden" name="rattache_a_chapitre" id="rattache_a_chapitre' . $rnd1 . '" value="' . html_attr($combo_rattache_a_chapitre->SelectedData) . '">';
	$combo_difficulte->Render();
	$combo_modele->HTML = '<span id="modele-container' . $rnd1 . '"></span><input type="hidden" name="modele" id="modele' . $rnd1 . '" value="' . html_attr($combo_modele->SelectedData) . '">';
	$combo_modele->MatchText = '<span id="modele-container-readonly' . $rnd1 . '"></span><input type="hidden" name="modele" id="modele' . $rnd1 . '" value="' . html_attr($combo_modele->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_rattache_a_chapitre__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['rattache_a_chapitre'] : $filterer_rattache_a_chapitre); ?>"};
		AppGini.current_modele__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['modele'] : $filterer_modele); ?>"};

		jQuery(function() {
			setTimeout(function(){
				if(typeof(rattache_a_chapitre_reload__RAND__) == 'function') rattache_a_chapitre_reload__RAND__();
				if(typeof(modele_reload__RAND__) == 'function') modele_reload__RAND__();
			}, 10); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function rattache_a_chapitre_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			$j("#rattache_a_chapitre-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_rattache_a_chapitre__RAND__.value, t: 'sequence', f: 'rattache_a_chapitre' },
						success: function(resp){
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="rattache_a_chapitre"]').val(resp.results[0].id);
							$j('[id=rattache_a_chapitre-container-readonly__RAND__]').html('<span id="rattache_a_chapitre-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=chapitre_view_parent]').hide(); }else{ $j('.btn[id=chapitre_view_parent]').show(); }


							if(typeof(rattache_a_chapitre_update_autofills__RAND__) == 'function') rattache_a_chapitre_update_autofills__RAND__();
						}
					});
				},
				width: ($j('fieldset .col-xs-11').width() - select2_max_width_decrement()) + 'px',
				formatNoMatches: function(term){ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ return { s: term, p: page, t: 'sequence', f: 'rattache_a_chapitre' }; },
					results: function(resp, page){ return resp; }
				},
				escapeMarkup: function(str){ return str; }
			}).on('change', function(e){
				AppGini.current_rattache_a_chapitre__RAND__.value = e.added.id;
				AppGini.current_rattache_a_chapitre__RAND__.text = e.added.text;
				$j('[name="rattache_a_chapitre"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=chapitre_view_parent]').hide(); }else{ $j('.btn[id=chapitre_view_parent]').show(); }


				if(typeof(rattache_a_chapitre_update_autofills__RAND__) == 'function') rattache_a_chapitre_update_autofills__RAND__();
			});

			if(!$j("#rattache_a_chapitre-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_rattache_a_chapitre__RAND__.value, t: 'sequence', f: 'rattache_a_chapitre' },
					success: function(resp){
						$j('[name="rattache_a_chapitre"]').val(resp.results[0].id);
						$j('[id=rattache_a_chapitre-container-readonly__RAND__]').html('<span id="rattache_a_chapitre-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=chapitre_view_parent]').hide(); }else{ $j('.btn[id=chapitre_view_parent]').show(); }

						if(typeof(rattache_a_chapitre_update_autofills__RAND__) == 'function') rattache_a_chapitre_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_rattache_a_chapitre__RAND__.value, t: 'sequence', f: 'rattache_a_chapitre' },
				success: function(resp){
					$j('[id=rattache_a_chapitre-container__RAND__], [id=rattache_a_chapitre-container-readonly__RAND__]').html('<span id="rattache_a_chapitre-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=chapitre_view_parent]').hide(); }else{ $j('.btn[id=chapitre_view_parent]').show(); }

					if(typeof(rattache_a_chapitre_update_autofills__RAND__) == 'function') rattache_a_chapitre_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function modele_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			$j("#modele-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_modele__RAND__.value, t: 'sequence', f: 'modele' },
						success: function(resp){
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="modele"]').val(resp.results[0].id);
							$j('[id=modele-container-readonly__RAND__]').html('<span id="modele-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=ref_sequences_view_parent]').hide(); }else{ $j('.btn[id=ref_sequences_view_parent]').show(); }


							if(typeof(modele_update_autofills__RAND__) == 'function') modele_update_autofills__RAND__();
						}
					});
				},
				width: ($j('fieldset .col-xs-11').width() - select2_max_width_decrement()) + 'px',
				formatNoMatches: function(term){ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ return { s: term, p: page, t: 'sequence', f: 'modele' }; },
					results: function(resp, page){ return resp; }
				},
				escapeMarkup: function(str){ return str; }
			}).on('change', function(e){
				AppGini.current_modele__RAND__.value = e.added.id;
				AppGini.current_modele__RAND__.text = e.added.text;
				$j('[name="modele"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=ref_sequences_view_parent]').hide(); }else{ $j('.btn[id=ref_sequences_view_parent]').show(); }


				if(typeof(modele_update_autofills__RAND__) == 'function') modele_update_autofills__RAND__();
			});

			if(!$j("#modele-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_modele__RAND__.value, t: 'sequence', f: 'modele' },
					success: function(resp){
						$j('[name="modele"]').val(resp.results[0].id);
						$j('[id=modele-container-readonly__RAND__]').html('<span id="modele-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=ref_sequences_view_parent]').hide(); }else{ $j('.btn[id=ref_sequences_view_parent]').show(); }

						if(typeof(modele_update_autofills__RAND__) == 'function') modele_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_modele__RAND__.value, t: 'sequence', f: 'modele' },
				success: function(resp){
					$j('[id=modele-container__RAND__], [id=modele-container-readonly__RAND__]').html('<span id="modele-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=ref_sequences_view_parent]').hide(); }else{ $j('.btn[id=ref_sequences_view_parent]').show(); }

					if(typeof(modele_update_autofills__RAND__) == 'function') modele_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	if($dvprint){
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/sequence_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	}else{
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/sequence_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Sequence details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert){
		if(!$selected_id) $templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return sequence_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return sequence_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']){
		$backAction = 'window.parent.jQuery(\'.modal\').modal(\'hide\'); return false;';
	}else{
		$backAction = '$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id){
		if(!$_REQUEST['Embedded']) $templateCode=str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate){
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return sequence_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)){
		$jsReadOnly .= "\tjQuery('#numero_ordre').replaceWith('<div class=\"form-control-static\" id=\"numero_ordre\">' + (jQuery('#numero_ordre').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#titre').replaceWith('<div class=\"form-control-static\" id=\"titre\">' + (jQuery('#titre').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#difficulte').replaceWith('<div class=\"form-control-static\" id=\"difficulte\">' + (jQuery('#difficulte').val() || '') + '</div>'); jQuery('#difficulte-multi-selection-help').hide();\n";
		$jsReadOnly .= "\tjQuery('#modele').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#modele_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	}elseif($AllowInsert){
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode=str_replace('<%%COMBO(rattache_a_chapitre)%%>', $combo_rattache_a_chapitre->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(rattache_a_chapitre)%%>', $combo_rattache_a_chapitre->MatchText, $templateCode);
	$templateCode=str_replace('<%%URLCOMBOTEXT(rattache_a_chapitre)%%>', urlencode($combo_rattache_a_chapitre->MatchText), $templateCode);
	$templateCode=str_replace('<%%COMBO(difficulte)%%>', $combo_difficulte->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(difficulte)%%>', $combo_difficulte->SelectedData, $templateCode);
	$templateCode=str_replace('<%%COMBO(modele)%%>', $combo_modele->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(modele)%%>', $combo_modele->MatchText, $templateCode);
	$templateCode=str_replace('<%%URLCOMBOTEXT(modele)%%>', urlencode($combo_modele->MatchText), $templateCode);

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array(  'rattache_a_chapitre' => array('chapitre', 'Rattach&#233; au chapitre'), 'modele' => array('ref_sequences', 'Modele'));
	foreach($lookup_fields as $luf => $ptfc){
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']){
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] && !$_REQUEST['Embedded']){
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode=str_replace('<%%UPLOADFILE(id_sequence)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(numero_ordre)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(titre)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(rattache_a_chapitre)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(difficulte)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(description)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(auteur)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(modele)%%>', '', $templateCode);

	// process values
	if($selected_id){
		$templateCode=str_replace('<%%VALUE(id_sequence)%%>', html_attr($row['id_sequence']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(id_sequence)%%>', urlencode($urow['id_sequence']), $templateCode);
		$templateCode=str_replace('<%%VALUE(numero_ordre)%%>', html_attr($row['numero_ordre']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(numero_ordre)%%>', urlencode($urow['numero_ordre']), $templateCode);
		$templateCode=str_replace('<%%VALUE(titre)%%>', html_attr($row['titre']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(titre)%%>', urlencode($urow['titre']), $templateCode);
		$templateCode=str_replace('<%%VALUE(rattache_a_chapitre)%%>', html_attr($row['rattache_a_chapitre']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(rattache_a_chapitre)%%>', urlencode($urow['rattache_a_chapitre']), $templateCode);
		$templateCode=str_replace('<%%VALUE(difficulte)%%>', html_attr($row['difficulte']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(difficulte)%%>', urlencode($urow['difficulte']), $templateCode);
		if($AllowUpdate || $AllowInsert){
			$templateCode = str_replace('<%%HTMLAREA(description)%%>', '<textarea name="description" id="description" rows="5">' . html_attr($row['description']) . '</textarea>', $templateCode);
		}else{
			$templateCode = str_replace('<%%HTMLAREA(description)%%>', '<div id="description" class="form-control-static">' . $row['description'] . '</div>', $templateCode);
		}
		$templateCode=str_replace('<%%VALUE(description)%%>', nl2br($row['description']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(description)%%>', urlencode($urow['description']), $templateCode);
		$templateCode=str_replace('<%%VALUE(auteur)%%>', html_attr($row['auteur']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(auteur)%%>', urlencode($urow['auteur']), $templateCode);
		$templateCode=str_replace('<%%VALUE(modele)%%>', html_attr($row['modele']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(modele)%%>', urlencode($urow['modele']), $templateCode);
	}else{
		$templateCode=str_replace('<%%VALUE(id_sequence)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(id_sequence)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(numero_ordre)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(numero_ordre)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(titre)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(titre)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(rattache_a_chapitre)%%>', ( $_REQUEST['FilterField'][1]=='4' && $_REQUEST['FilterOperator'][1]=='<=>' ? $combo_rattache_a_chapitre->SelectedData : ''), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(rattache_a_chapitre)%%>', urlencode( $_REQUEST['FilterField'][1]=='4' && $_REQUEST['FilterOperator'][1]=='<=>' ? $combo_rattache_a_chapitre->SelectedData : ''), $templateCode);
		$templateCode=str_replace('<%%VALUE(difficulte)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(difficulte)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%HTMLAREA(description)%%>', '<textarea name="description" id="description" rows="5"></textarea>', $templateCode);
		$templateCode=str_replace('<%%VALUE(auteur)%%>', '<%%creatorUsername%%>', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(auteur)%%>', urlencode('<%%creatorUsername%%>'), $templateCode);
		$templateCode=str_replace('<%%VALUE(modele)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(modele)%%>', urlencode(''), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode=str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode=str_replace('<%%', '<!-- ', $templateCode);
	$templateCode=str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == ''){
		$templateCode .= "\n\n<script>\$j(function(){\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption){
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id){
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('sequence');
	if($selected_id){
		$jdata = get_joined_record('sequence', $selected_id);
		$rdata = $row;
	}
	$cache_data = array(
		'rdata' => array_map('nl2br', array_map('addslashes', $rdata)),
		'jdata' => array_map('nl2br', array_map('addslashes', $jdata)),
	);
	$templateCode .= loadView('sequence-ajax-cache', $cache_data);

	// hook: sequence_dv
	if(function_exists('sequence_dv')){
		$args=array();
		sequence_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>